// This file is auto-generated by @hey-api/openapi-ts

import type { GetBotsByBotIdMessagesLocateResponse, GetBotsByBotIdMessagesResponse } from './types.gen';

const conversationUiTurnSchemaResponseTransformer = (data: any) => {
    data.timestamp = new Date(data.timestamp);
    return data;
};

const handlersUiMessageListResponseSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => conversationUiTurnSchemaResponseTransformer(item));
    return data;
};

export const getBotsByBotIdMessagesResponseTransformer = async (data: any): Promise<GetBotsByBotIdMessagesResponse> => {
    data = handlersUiMessageListResponseSchemaResponseTransformer(data);
    return data;
};

const handlersUiLocateMessageResponseSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => conversationUiTurnSchemaResponseTransformer(item));
    return data;
};

export const getBotsByBotIdMessagesLocateResponseTransformer = async (data: any): Promise<GetBotsByBotIdMessagesLocateResponse> => {
    data = handlersUiLocateMessageResponseSchemaResponseTransformer(data);
    return data;
};
