// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearBotRuntimeData = `-- name: ClearBotRuntimeData :exec
WITH target_sessions AS MATERIALIZED (
  SELECT session.id
  FROM bot_sessions session
  WHERE session.team_id = public.sophia_current_team_id()
    AND session.bot_id = $1
  ORDER BY session.id
  FOR UPDATE
),
target_compaction_artifacts AS MATERIALIZED (
  SELECT compact.id
  FROM bot_history_message_compacts compact
  WHERE compact.team_id = public.sophia_current_team_id()
    AND compact.bot_id = $1
    AND (SELECT count(*) FROM target_sessions) >= 0
  ORDER BY compact.id
  FOR UPDATE
),
deleted_compaction_artifacts AS (
  DELETE FROM bot_history_message_compacts compact
  USING target_compaction_artifacts target
  WHERE compact.team_id = public.sophia_current_team_id()
    AND compact.id = target.id
  RETURNING compact.id
),
target_messages AS MATERIALIZED (
  SELECT message.id
  FROM bot_history_messages message
  WHERE message.team_id = public.sophia_current_team_id()
    AND message.bot_id = $1
    AND (SELECT count(*) FROM target_sessions) >= 0
    AND (SELECT count(*) FROM deleted_compaction_artifacts) >= 0
  ORDER BY message.id
  FOR UPDATE
),
deleted_messages AS (
  DELETE FROM bot_history_messages message
  USING target_messages target
  WHERE message.team_id = public.sophia_current_team_id()
    AND message.id = target.id
  RETURNING message.id
),
deleted_sessions AS (
  DELETE FROM bot_sessions session
  USING target_sessions target
  WHERE session.team_id = public.sophia_current_team_id()
    AND session.id = target.id
    AND (SELECT count(*) FROM deleted_messages) >= 0
  RETURNING session.id
)
DELETE FROM bot_channel_routes route
WHERE route.team_id = public.sophia_current_team_id()
  AND route.bot_id = $1
  AND (SELECT count(*) FROM deleted_sessions) >= 0
`

func (q *Queries) ClearBotRuntimeData(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearBotRuntimeData, botID)
	return err
}

const createBot = `-- name: CreateBot :one
INSERT INTO bots (owner_user_id, name, display_name, avatar_url, timezone, is_active, metadata, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, metadata, created_at, updated_at
`

type CreateBotParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	Name        string      `json:"name"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Timezone    pgtype.Text `json:"timezone"`
	IsActive    bool        `json:"is_active"`
	Metadata    []byte      `json:"metadata"`
	Status      string      `json:"status"`
}

type CreateBotRow struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	Name              string             `json:"name"`
	DisplayName       pgtype.Text        `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Timezone          pgtype.Text        `json:"timezone"`
	IsActive          bool               `json:"is_active"`
	Status            string             `json:"status"`
	Language          string             `json:"language"`
	ReasoningEnabled  bool               `json:"reasoning_enabled"`
	ReasoningEffort   string             `json:"reasoning_effort"`
	ChatModelID       pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID  pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID  pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled  bool               `json:"heartbeat_enabled"`
	HeartbeatInterval int32              `json:"heartbeat_interval"`
	HeartbeatPrompt   string             `json:"heartbeat_prompt"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (CreateBotRow, error) {
	row := q.db.QueryRow(ctx, createBot,
		arg.OwnerUserID,
		arg.Name,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Timezone,
		arg.IsActive,
		arg.Metadata,
		arg.Status,
	)
	var i CreateBotRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBotByID = `-- name: DeleteBotByID :exec
WITH target_sessions AS MATERIALIZED (
  SELECT session.id
  FROM bot_sessions session
  WHERE session.team_id = public.sophia_current_team_id()
    AND session.bot_id = $1
  ORDER BY session.id
  FOR UPDATE
),
target_compaction_artifacts AS MATERIALIZED (
  SELECT compact.id
  FROM bot_history_message_compacts compact
  WHERE compact.team_id = public.sophia_current_team_id()
    AND compact.bot_id = $1
    AND (SELECT count(*) FROM target_sessions) >= 0
  ORDER BY compact.id
  FOR UPDATE
),
deleted_compaction_artifacts AS (
  DELETE FROM bot_history_message_compacts compact
  USING target_compaction_artifacts target
  WHERE compact.team_id = public.sophia_current_team_id()
    AND compact.id = target.id
  RETURNING compact.id
),
target_messages AS MATERIALIZED (
  SELECT message.id
  FROM bot_history_messages message
  WHERE message.team_id = public.sophia_current_team_id()
    AND message.bot_id = $1
    AND (SELECT count(*) FROM target_sessions) >= 0
    AND (SELECT count(*) FROM deleted_compaction_artifacts) >= 0
  ORDER BY message.id
  FOR UPDATE
),
deleted_messages AS (
  DELETE FROM bot_history_messages message
  USING target_messages target
  WHERE message.team_id = public.sophia_current_team_id()
    AND message.id = target.id
  RETURNING message.id
),
deleted_sessions AS (
  DELETE FROM bot_sessions session
  USING target_sessions target
  WHERE session.team_id = public.sophia_current_team_id()
    AND session.id = target.id
    AND (SELECT count(*) FROM deleted_messages) >= 0
  RETURNING session.id
)
DELETE FROM bots bot
WHERE bot.team_id = public.sophia_current_team_id()
  AND bot.id = $1
  AND (SELECT count(*) FROM target_sessions) >= 0
  AND (SELECT count(*) FROM deleted_sessions) >= 0
`

func (q *Queries) DeleteBotByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBotByID, id)
	return err
}

const getBotByID = `-- name: GetBotByID :one
SELECT id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, compaction_enabled, compaction_threshold, compaction_target_percent, compaction_model_id, metadata, created_at, updated_at
FROM bots
WHERE team_id = public.sophia_current_team_id() AND id = $1
`

type GetBotByIDRow struct {
	ID                      pgtype.UUID        `json:"id"`
	OwnerUserID             pgtype.UUID        `json:"owner_user_id"`
	Name                    string             `json:"name"`
	DisplayName             pgtype.Text        `json:"display_name"`
	AvatarUrl               pgtype.Text        `json:"avatar_url"`
	Timezone                pgtype.Text        `json:"timezone"`
	IsActive                bool               `json:"is_active"`
	Status                  string             `json:"status"`
	Language                string             `json:"language"`
	ReasoningEnabled        bool               `json:"reasoning_enabled"`
	ReasoningEffort         string             `json:"reasoning_effort"`
	ChatModelID             pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID        pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID        pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled        bool               `json:"heartbeat_enabled"`
	HeartbeatInterval       int32              `json:"heartbeat_interval"`
	HeartbeatPrompt         string             `json:"heartbeat_prompt"`
	CompactionEnabled       bool               `json:"compaction_enabled"`
	CompactionThreshold     int32              `json:"compaction_threshold"`
	CompactionTargetPercent pgtype.Int4        `json:"compaction_target_percent"`
	CompactionModelID       pgtype.UUID        `json:"compaction_model_id"`
	Metadata                []byte             `json:"metadata"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetBotByID(ctx context.Context, id pgtype.UUID) (GetBotByIDRow, error) {
	row := q.db.QueryRow(ctx, getBotByID, id)
	var i GetBotByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionTargetPercent,
		&i.CompactionModelID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotByName = `-- name: GetBotByName :one
SELECT id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, compaction_enabled, compaction_threshold, compaction_target_percent, compaction_model_id, metadata, created_at, updated_at
FROM bots
WHERE team_id = public.sophia_current_team_id() AND name = $1
`

type GetBotByNameRow struct {
	ID                      pgtype.UUID        `json:"id"`
	OwnerUserID             pgtype.UUID        `json:"owner_user_id"`
	Name                    string             `json:"name"`
	DisplayName             pgtype.Text        `json:"display_name"`
	AvatarUrl               pgtype.Text        `json:"avatar_url"`
	Timezone                pgtype.Text        `json:"timezone"`
	IsActive                bool               `json:"is_active"`
	Status                  string             `json:"status"`
	Language                string             `json:"language"`
	ReasoningEnabled        bool               `json:"reasoning_enabled"`
	ReasoningEffort         string             `json:"reasoning_effort"`
	ChatModelID             pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID        pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID        pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled        bool               `json:"heartbeat_enabled"`
	HeartbeatInterval       int32              `json:"heartbeat_interval"`
	HeartbeatPrompt         string             `json:"heartbeat_prompt"`
	CompactionEnabled       bool               `json:"compaction_enabled"`
	CompactionThreshold     int32              `json:"compaction_threshold"`
	CompactionTargetPercent pgtype.Int4        `json:"compaction_target_percent"`
	CompactionModelID       pgtype.UUID        `json:"compaction_model_id"`
	Metadata                []byte             `json:"metadata"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetBotByName(ctx context.Context, name string) (GetBotByNameRow, error) {
	row := q.db.QueryRow(ctx, getBotByName, name)
	var i GetBotByNameRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionTargetPercent,
		&i.CompactionModelID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccessibleBots = `-- name: ListAccessibleBots :many
SELECT id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, metadata, created_at, updated_at
FROM bots b
WHERE b.team_id = public.sophia_current_team_id()
  AND (
    b.owner_user_id = $1
    OR EXISTS (
      SELECT 1 FROM bot_user_grants g
      WHERE g.team_id = b.team_id
        AND g.bot_id = b.id
        AND (
          g.subject_type = 'everyone'
          OR (g.subject_type = 'user' AND g.user_id = $1)
        )
    )
  )
ORDER BY b.created_at DESC
`

type ListAccessibleBotsRow struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	Name              string             `json:"name"`
	DisplayName       pgtype.Text        `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Timezone          pgtype.Text        `json:"timezone"`
	IsActive          bool               `json:"is_active"`
	Status            string             `json:"status"`
	Language          string             `json:"language"`
	ReasoningEnabled  bool               `json:"reasoning_enabled"`
	ReasoningEffort   string             `json:"reasoning_effort"`
	ChatModelID       pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID  pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID  pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled  bool               `json:"heartbeat_enabled"`
	HeartbeatInterval int32              `json:"heartbeat_interval"`
	HeartbeatPrompt   string             `json:"heartbeat_prompt"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAccessibleBots(ctx context.Context, ownerUserID pgtype.UUID) ([]ListAccessibleBotsRow, error) {
	rows, err := q.db.Query(ctx, listAccessibleBots, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessibleBotsRow
	for rows.Next() {
		var i ListAccessibleBotsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Timezone,
			&i.IsActive,
			&i.Status,
			&i.Language,
			&i.ReasoningEnabled,
			&i.ReasoningEffort,
			&i.ChatModelID,
			&i.SearchProviderID,
			&i.MemoryProviderID,
			&i.HeartbeatEnabled,
			&i.HeartbeatInterval,
			&i.HeartbeatPrompt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBotsByOwner = `-- name: ListBotsByOwner :many
SELECT id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, metadata, created_at, updated_at
FROM bots
WHERE team_id = public.sophia_current_team_id() AND owner_user_id = $1
ORDER BY created_at DESC
`

type ListBotsByOwnerRow struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	Name              string             `json:"name"`
	DisplayName       pgtype.Text        `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Timezone          pgtype.Text        `json:"timezone"`
	IsActive          bool               `json:"is_active"`
	Status            string             `json:"status"`
	Language          string             `json:"language"`
	ReasoningEnabled  bool               `json:"reasoning_enabled"`
	ReasoningEffort   string             `json:"reasoning_effort"`
	ChatModelID       pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID  pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID  pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled  bool               `json:"heartbeat_enabled"`
	HeartbeatInterval int32              `json:"heartbeat_interval"`
	HeartbeatPrompt   string             `json:"heartbeat_prompt"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListBotsByOwner(ctx context.Context, ownerUserID pgtype.UUID) ([]ListBotsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listBotsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBotsByOwnerRow
	for rows.Next() {
		var i ListBotsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Timezone,
			&i.IsActive,
			&i.Status,
			&i.Language,
			&i.ReasoningEnabled,
			&i.ReasoningEffort,
			&i.ChatModelID,
			&i.SearchProviderID,
			&i.MemoryProviderID,
			&i.HeartbeatEnabled,
			&i.HeartbeatInterval,
			&i.HeartbeatPrompt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeartbeatEnabledBots = `-- name: ListHeartbeatEnabledBots :many
SELECT id, owner_user_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt
FROM bots
WHERE team_id = public.sophia_current_team_id() AND heartbeat_enabled = true AND status = 'ready'
`

type ListHeartbeatEnabledBotsRow struct {
	ID                pgtype.UUID `json:"id"`
	OwnerUserID       pgtype.UUID `json:"owner_user_id"`
	HeartbeatEnabled  bool        `json:"heartbeat_enabled"`
	HeartbeatInterval int32       `json:"heartbeat_interval"`
	HeartbeatPrompt   string      `json:"heartbeat_prompt"`
}

func (q *Queries) ListHeartbeatEnabledBots(ctx context.Context) ([]ListHeartbeatEnabledBotsRow, error) {
	rows, err := q.db.Query(ctx, listHeartbeatEnabledBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHeartbeatEnabledBotsRow
	for rows.Next() {
		var i ListHeartbeatEnabledBotsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.HeartbeatEnabled,
			&i.HeartbeatInterval,
			&i.HeartbeatPrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBotForSessionWrite = `-- name: LockBotForSessionWrite :one
SELECT id
FROM bots
WHERE team_id = public.sophia_current_team_id()
  AND id = $1
FOR KEY SHARE
`

func (q *Queries) LockBotForSessionWrite(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockBotForSessionWrite, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const touchBotActivity = `-- name: TouchBotActivity :exec
UPDATE bots
SET updated_at = now()
WHERE team_id = public.sophia_current_team_id() AND id = $1
`

func (q *Queries) TouchBotActivity(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchBotActivity, botID)
	return err
}

const updateBotOwner = `-- name: UpdateBotOwner :one
UPDATE bots
SET owner_user_id = $2,
    updated_at = now()
WHERE team_id = public.sophia_current_team_id() AND id = $1
RETURNING id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, metadata, created_at, updated_at
`

type UpdateBotOwnerParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

type UpdateBotOwnerRow struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	Name              string             `json:"name"`
	DisplayName       pgtype.Text        `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Timezone          pgtype.Text        `json:"timezone"`
	IsActive          bool               `json:"is_active"`
	Status            string             `json:"status"`
	Language          string             `json:"language"`
	ReasoningEnabled  bool               `json:"reasoning_enabled"`
	ReasoningEffort   string             `json:"reasoning_effort"`
	ChatModelID       pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID  pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID  pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled  bool               `json:"heartbeat_enabled"`
	HeartbeatInterval int32              `json:"heartbeat_interval"`
	HeartbeatPrompt   string             `json:"heartbeat_prompt"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateBotOwner(ctx context.Context, arg UpdateBotOwnerParams) (UpdateBotOwnerRow, error) {
	row := q.db.QueryRow(ctx, updateBotOwner, arg.ID, arg.OwnerUserID)
	var i UpdateBotOwnerRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBotProfile = `-- name: UpdateBotProfile :one
UPDATE bots
SET name = $2,
    display_name = $3,
    avatar_url = $4,
    timezone = $5,
    is_active = $6,
    metadata = $7,
    updated_at = now()
WHERE team_id = public.sophia_current_team_id() AND id = $1
RETURNING id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, metadata, created_at, updated_at
`

type UpdateBotProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Timezone    pgtype.Text `json:"timezone"`
	IsActive    bool        `json:"is_active"`
	Metadata    []byte      `json:"metadata"`
}

type UpdateBotProfileRow struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	Name              string             `json:"name"`
	DisplayName       pgtype.Text        `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Timezone          pgtype.Text        `json:"timezone"`
	IsActive          bool               `json:"is_active"`
	Status            string             `json:"status"`
	Language          string             `json:"language"`
	ReasoningEnabled  bool               `json:"reasoning_enabled"`
	ReasoningEffort   string             `json:"reasoning_effort"`
	ChatModelID       pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID  pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID  pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled  bool               `json:"heartbeat_enabled"`
	HeartbeatInterval int32              `json:"heartbeat_interval"`
	HeartbeatPrompt   string             `json:"heartbeat_prompt"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateBotProfile(ctx context.Context, arg UpdateBotProfileParams) (UpdateBotProfileRow, error) {
	row := q.db.QueryRow(ctx, updateBotProfile,
		arg.ID,
		arg.Name,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Timezone,
		arg.IsActive,
		arg.Metadata,
	)
	var i UpdateBotProfileRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBotStatus = `-- name: UpdateBotStatus :exec
UPDATE bots
SET status = $2,
    updated_at = now()
WHERE team_id = public.sophia_current_team_id() AND id = $1
`

type UpdateBotStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateBotStatus(ctx context.Context, arg UpdateBotStatusParams) error {
	_, err := q.db.Exec(ctx, updateBotStatus, arg.ID, arg.Status)
	return err
}
