// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connectors.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConnector = `-- name: CreateConnector :one
INSERT INTO connectors (bot_id, connection_id, alias)
VALUES ($1, $2, $3)
RETURNING team_id, bot_id, connection_id, alias, enabled, created_at, updated_at
`

type CreateConnectorParams struct {
	BotID        pgtype.UUID `json:"bot_id"`
	ConnectionID string      `json:"connection_id"`
	Alias        string      `json:"alias"`
}

func (q *Queries) CreateConnector(ctx context.Context, arg CreateConnectorParams) (Connector, error) {
	row := q.db.QueryRow(ctx, createConnector, arg.BotID, arg.ConnectionID, arg.Alias)
	var i Connector
	err := row.Scan(
		&i.TeamID,
		&i.BotID,
		&i.ConnectionID,
		&i.Alias,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConnector = `-- name: DeleteConnector :exec
DELETE FROM connectors
WHERE team_id = public.sophia_current_team_id()
  AND bot_id = $1
  AND connection_id = $2
`

type DeleteConnectorParams struct {
	BotID        pgtype.UUID `json:"bot_id"`
	ConnectionID string      `json:"connection_id"`
}

func (q *Queries) DeleteConnector(ctx context.Context, arg DeleteConnectorParams) error {
	_, err := q.db.Exec(ctx, deleteConnector, arg.BotID, arg.ConnectionID)
	return err
}

const getConnectorByConnectionID = `-- name: GetConnectorByConnectionID :one
SELECT team_id, bot_id, connection_id, alias, enabled, created_at, updated_at
FROM connectors
WHERE team_id = public.sophia_current_team_id()
  AND bot_id = $1
  AND connection_id = $2
LIMIT 1
`

type GetConnectorByConnectionIDParams struct {
	BotID        pgtype.UUID `json:"bot_id"`
	ConnectionID string      `json:"connection_id"`
}

func (q *Queries) GetConnectorByConnectionID(ctx context.Context, arg GetConnectorByConnectionIDParams) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnectorByConnectionID, arg.BotID, arg.ConnectionID)
	var i Connector
	err := row.Scan(
		&i.TeamID,
		&i.BotID,
		&i.ConnectionID,
		&i.Alias,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectorsByBotID = `-- name: ListConnectorsByBotID :many
SELECT team_id, bot_id, connection_id, alias, enabled, created_at, updated_at
FROM connectors
WHERE team_id = public.sophia_current_team_id()
  AND bot_id = $1
ORDER BY connection_id ASC
`

func (q *Queries) ListConnectorsByBotID(ctx context.Context, botID pgtype.UUID) ([]Connector, error) {
	rows, err := q.db.Query(ctx, listConnectorsByBotID, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connector
	for rows.Next() {
		var i Connector
		if err := rows.Scan(
			&i.TeamID,
			&i.BotID,
			&i.ConnectionID,
			&i.Alias,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnectorEnabled = `-- name: UpdateConnectorEnabled :execrows
UPDATE connectors
SET enabled = $3,
    updated_at = now()
WHERE team_id = public.sophia_current_team_id()
  AND bot_id = $1
  AND connection_id = $2
`

type UpdateConnectorEnabledParams struct {
	BotID        pgtype.UUID `json:"bot_id"`
	ConnectionID string      `json:"connection_id"`
	Enabled      bool        `json:"enabled"`
}

func (q *Queries) UpdateConnectorEnabled(ctx context.Context, arg UpdateConnectorEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateConnectorEnabled, arg.BotID, arg.ConnectionID, arg.Enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
