// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMessageAssetsByBot = `-- name: CountMessageAssetsByBot :one
SELECT COUNT(*)
FROM bot_history_message_assets a
JOIN bot_history_messages m ON m.id = a.message_id
WHERE a.team_id = public.sophia_current_team_id() AND m.team_id = public.sophia_current_team_id() AND m.bot_id = $1
`

func (q *Queries) CountMessageAssetsByBot(ctx context.Context, botID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMessageAssetsByBot, botID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessageAsset = `-- name: CreateMessageAsset :one
WITH message_locator AS MATERIALIZED (
  SELECT message.id, message.session_id
  FROM bot_history_messages message
  WHERE message.team_id = public.sophia_current_team_id()
    AND message.id = $1
),
owner_session AS MATERIALIZED (
  SELECT session.id, session.bot_id, session.compaction_epoch
  FROM bot_sessions session
  JOIN message_locator message
    ON message.session_id = session.id
   AND session.team_id = public.sophia_current_team_id()
  FOR UPDATE
),
target_message AS MATERIALIZED (
  SELECT message.id, message.session_id, message.compact_id
  FROM bot_history_messages message
  JOIN message_locator locator ON locator.id = message.id
  LEFT JOIN owner_session owner ON owner.id = locator.session_id
  WHERE message.team_id = public.sophia_current_team_id()
    AND (locator.session_id IS NULL OR owner.id IS NOT NULL)
  FOR UPDATE OF message
),
changed_asset AS MATERIALIZED (
  SELECT target.id, target.session_id, target.compact_id
  FROM target_message target
  LEFT JOIN bot_history_message_assets existing
    ON existing.message_id = target.id
   AND existing.team_id = public.sophia_current_team_id()
   AND existing.content_hash = $2
  WHERE existing.id IS NULL
     OR existing.role IS DISTINCT FROM $3
     OR existing.ordinal IS DISTINCT FROM $4
     OR existing.name IS DISTINCT FROM $5
     OR existing.metadata IS DISTINCT FROM $6
),
invalidated_session AS (
  UPDATE bot_sessions session
  SET compaction_epoch = session.compaction_epoch + 1
  FROM changed_asset changed
  JOIN owner_session owner ON owner.id = changed.session_id
  JOIN bot_history_message_compacts compact
    ON compact.id = changed.compact_id
   AND compact.team_id = public.sophia_current_team_id()
  WHERE session.team_id = public.sophia_current_team_id()
    AND session.id = owner.id
    AND compact.bot_id = owner.bot_id
    AND compact.session_id = owner.id
    AND compact.compaction_epoch = owner.compaction_epoch
    AND compact.status IN ('pending', 'ok')
  RETURNING session.id
),
upserted_asset AS (
  INSERT INTO bot_history_message_assets (
    message_id, role, ordinal, content_hash, mime, size_bytes, storage_key, name, metadata
  )
  SELECT
    target.id,
    $3,
    $4,
    $2,
    COALESCE($7::text, ''),
    $8,
    COALESCE($9::text, ''),
    $5,
    $6
  FROM target_message target
  CROSS JOIN (SELECT count(*) FROM invalidated_session) invalidation_done
  ON CONFLICT (team_id, message_id, content_hash) DO UPDATE SET
    role = EXCLUDED.role,
    ordinal = EXCLUDED.ordinal,
    mime = CASE WHEN EXCLUDED.mime <> '' THEN EXCLUDED.mime ELSE bot_history_message_assets.mime END,
    size_bytes = CASE WHEN EXCLUDED.size_bytes > 0 THEN EXCLUDED.size_bytes ELSE bot_history_message_assets.size_bytes END,
    storage_key = CASE WHEN EXCLUDED.storage_key <> '' THEN EXCLUDED.storage_key ELSE bot_history_message_assets.storage_key END,
    name = EXCLUDED.name,
    metadata = EXCLUDED.metadata
  RETURNING id, message_id, role, ordinal, content_hash, mime, size_bytes, storage_key, name, metadata, created_at
)
SELECT id, message_id, role, ordinal, content_hash, mime, size_bytes, storage_key, name, metadata, created_at
FROM upserted_asset
`

type CreateMessageAssetParams struct {
	MessageID   pgtype.UUID `json:"message_id"`
	ContentHash string      `json:"content_hash"`
	Role        string      `json:"role"`
	Ordinal     int32       `json:"ordinal"`
	Name        string      `json:"name"`
	Metadata    []byte      `json:"metadata"`
	Mime        string      `json:"mime"`
	SizeBytes   int64       `json:"size_bytes"`
	StorageKey  string      `json:"storage_key"`
}

type CreateMessageAssetRow struct {
	ID          pgtype.UUID        `json:"id"`
	MessageID   pgtype.UUID        `json:"message_id"`
	Role        string             `json:"role"`
	Ordinal     int32              `json:"ordinal"`
	ContentHash string             `json:"content_hash"`
	Mime        string             `json:"mime"`
	SizeBytes   int64              `json:"size_bytes"`
	StorageKey  string             `json:"storage_key"`
	Name        string             `json:"name"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateMessageAsset(ctx context.Context, arg CreateMessageAssetParams) (CreateMessageAssetRow, error) {
	row := q.db.QueryRow(ctx, createMessageAsset,
		arg.MessageID,
		arg.ContentHash,
		arg.Role,
		arg.Ordinal,
		arg.Name,
		arg.Metadata,
		arg.Mime,
		arg.SizeBytes,
		arg.StorageKey,
	)
	var i CreateMessageAssetRow
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Role,
		&i.Ordinal,
		&i.ContentHash,
		&i.Mime,
		&i.SizeBytes,
		&i.StorageKey,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createStorageProvider = `-- name: CreateStorageProvider :one
INSERT INTO storage_providers (name, provider, config)
VALUES ($1, $2, $3)
RETURNING id, name, provider, config, created_at, updated_at, team_id
`

type CreateStorageProviderParams struct {
	Name     string `json:"name"`
	Provider string `json:"provider"`
	Config   []byte `json:"config"`
}

func (q *Queries) CreateStorageProvider(ctx context.Context, arg CreateStorageProviderParams) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, createStorageProvider, arg.Name, arg.Provider, arg.Config)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const deleteMessageAssets = `-- name: DeleteMessageAssets :exec
DELETE FROM bot_history_message_assets WHERE team_id = public.sophia_current_team_id() AND message_id = $1
`

func (q *Queries) DeleteMessageAssets(ctx context.Context, messageID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessageAssets, messageID)
	return err
}

const getBotStorageBinding = `-- name: GetBotStorageBinding :one
SELECT id, bot_id, storage_provider_id, base_path, created_at, updated_at, team_id FROM bot_storage_bindings WHERE team_id = public.sophia_current_team_id() AND bot_id = $1
`

func (q *Queries) GetBotStorageBinding(ctx context.Context, botID pgtype.UUID) (BotStorageBinding, error) {
	row := q.db.QueryRow(ctx, getBotStorageBinding, botID)
	var i BotStorageBinding
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.StorageProviderID,
		&i.BasePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const getStorageProviderByID = `-- name: GetStorageProviderByID :one
SELECT id, name, provider, config, created_at, updated_at, team_id FROM storage_providers WHERE team_id = public.sophia_current_team_id() AND id = $1
`

func (q *Queries) GetStorageProviderByID(ctx context.Context, id pgtype.UUID) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, getStorageProviderByID, id)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const getStorageProviderByName = `-- name: GetStorageProviderByName :one
SELECT id, name, provider, config, created_at, updated_at, team_id FROM storage_providers WHERE team_id = public.sophia_current_team_id() AND name = $1
`

func (q *Queries) GetStorageProviderByName(ctx context.Context, name string) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, getStorageProviderByName, name)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const listMessageAssets = `-- name: ListMessageAssets :many
SELECT id AS rel_id, message_id, role, ordinal, content_hash, mime, size_bytes, storage_key, name, metadata
FROM bot_history_message_assets
WHERE team_id = public.sophia_current_team_id() AND message_id = $1
ORDER BY ordinal ASC
`

type ListMessageAssetsRow struct {
	RelID       pgtype.UUID `json:"rel_id"`
	MessageID   pgtype.UUID `json:"message_id"`
	Role        string      `json:"role"`
	Ordinal     int32       `json:"ordinal"`
	ContentHash string      `json:"content_hash"`
	Mime        string      `json:"mime"`
	SizeBytes   int64       `json:"size_bytes"`
	StorageKey  string      `json:"storage_key"`
	Name        string      `json:"name"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) ListMessageAssets(ctx context.Context, messageID pgtype.UUID) ([]ListMessageAssetsRow, error) {
	rows, err := q.db.Query(ctx, listMessageAssets, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessageAssetsRow
	for rows.Next() {
		var i ListMessageAssetsRow
		if err := rows.Scan(
			&i.RelID,
			&i.MessageID,
			&i.Role,
			&i.Ordinal,
			&i.ContentHash,
			&i.Mime,
			&i.SizeBytes,
			&i.StorageKey,
			&i.Name,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageAssetsBatch = `-- name: ListMessageAssetsBatch :many
SELECT id AS rel_id, message_id, role, ordinal, content_hash, mime, size_bytes, storage_key, name, metadata
FROM bot_history_message_assets
WHERE team_id = public.sophia_current_team_id() AND message_id = ANY($1::uuid[])
ORDER BY message_id, ordinal ASC
`

type ListMessageAssetsBatchRow struct {
	RelID       pgtype.UUID `json:"rel_id"`
	MessageID   pgtype.UUID `json:"message_id"`
	Role        string      `json:"role"`
	Ordinal     int32       `json:"ordinal"`
	ContentHash string      `json:"content_hash"`
	Mime        string      `json:"mime"`
	SizeBytes   int64       `json:"size_bytes"`
	StorageKey  string      `json:"storage_key"`
	Name        string      `json:"name"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) ListMessageAssetsBatch(ctx context.Context, messageIds []pgtype.UUID) ([]ListMessageAssetsBatchRow, error) {
	rows, err := q.db.Query(ctx, listMessageAssetsBatch, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessageAssetsBatchRow
	for rows.Next() {
		var i ListMessageAssetsBatchRow
		if err := rows.Scan(
			&i.RelID,
			&i.MessageID,
			&i.Role,
			&i.Ordinal,
			&i.ContentHash,
			&i.Mime,
			&i.SizeBytes,
			&i.StorageKey,
			&i.Name,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageProviders = `-- name: ListStorageProviders :many
SELECT id, name, provider, config, created_at, updated_at, team_id FROM storage_providers WHERE team_id = public.sophia_current_team_id() ORDER BY created_at DESC
`

func (q *Queries) ListStorageProviders(ctx context.Context) ([]StorageProvider, error) {
	rows, err := q.db.Query(ctx, listStorageProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageProvider
	for rows.Next() {
		var i StorageProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBotStorageBinding = `-- name: UpsertBotStorageBinding :one
INSERT INTO bot_storage_bindings (bot_id, storage_provider_id, base_path)
VALUES ($1, $2, $3)
ON CONFLICT (team_id, bot_id) DO UPDATE SET
  storage_provider_id = EXCLUDED.storage_provider_id,
  base_path = EXCLUDED.base_path,
  updated_at = now()
RETURNING id, bot_id, storage_provider_id, base_path, created_at, updated_at, team_id
`

type UpsertBotStorageBindingParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	StorageProviderID pgtype.UUID `json:"storage_provider_id"`
	BasePath          string      `json:"base_path"`
}

func (q *Queries) UpsertBotStorageBinding(ctx context.Context, arg UpsertBotStorageBindingParams) (BotStorageBinding, error) {
	row := q.db.QueryRow(ctx, upsertBotStorageBinding, arg.BotID, arg.StorageProviderID, arg.BasePath)
	var i BotStorageBinding
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.StorageProviderID,
		&i.BasePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}
