// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory_wiki.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMemoryEdgesByBot = `-- name: CountMemoryEdgesByBot :one
SELECT COUNT(*) FROM memory_edges
WHERE team_id = public.sophia_current_team_id() AND bot_id = $1
`

func (q *Queries) CountMemoryEdgesByBot(ctx context.Context, botID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMemoryEdgesByBot, botID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMemoryNodesByBot = `-- name: CountMemoryNodesByBot :one
SELECT COUNT(*) FROM memory_nodes
WHERE team_id = public.sophia_current_team_id() AND bot_id = $1
`

func (q *Queries) CountMemoryNodesByBot(ctx context.Context, botID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMemoryNodesByBot, botID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllMemoryEdgesByBot = `-- name: DeleteAllMemoryEdgesByBot :exec
DELETE FROM memory_edges
WHERE team_id = public.sophia_current_team_id() AND bot_id = $1
`

func (q *Queries) DeleteAllMemoryEdgesByBot(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllMemoryEdgesByBot, botID)
	return err
}

const deleteAllMemoryNodesByBot = `-- name: DeleteAllMemoryNodesByBot :exec
DELETE FROM memory_nodes
WHERE team_id = public.sophia_current_team_id() AND bot_id = $1
`

func (q *Queries) DeleteAllMemoryNodesByBot(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllMemoryNodesByBot, botID)
	return err
}

const deleteMemoryEdgesByRelForBot = `-- name: DeleteMemoryEdgesByRelForBot :exec
DELETE FROM memory_edges
WHERE team_id = public.sophia_current_team_id() AND bot_id = $1 AND rel = $2
`

type DeleteMemoryEdgesByRelForBotParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	Rel   string      `json:"rel"`
}

func (q *Queries) DeleteMemoryEdgesByRelForBot(ctx context.Context, arg DeleteMemoryEdgesByRelForBotParams) error {
	_, err := q.db.Exec(ctx, deleteMemoryEdgesByRelForBot, arg.BotID, arg.Rel)
	return err
}

const deleteMemoryEdgesForNode = `-- name: DeleteMemoryEdgesForNode :exec
DELETE FROM memory_edges
WHERE team_id = public.sophia_current_team_id() AND bot_id = $1 AND (src_node = $2 OR dst_node = $2)
`

type DeleteMemoryEdgesForNodeParams struct {
	BotID   pgtype.UUID `json:"bot_id"`
	SrcNode string      `json:"src_node"`
}

func (q *Queries) DeleteMemoryEdgesForNode(ctx context.Context, arg DeleteMemoryEdgesForNodeParams) error {
	_, err := q.db.Exec(ctx, deleteMemoryEdgesForNode, arg.BotID, arg.SrcNode)
	return err
}

const deleteMemoryNode = `-- name: DeleteMemoryNode :exec
DELETE FROM memory_nodes
WHERE team_id = public.sophia_current_team_id() AND bot_id = $1 AND id = $2
`

type DeleteMemoryNodeParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	ID    string      `json:"id"`
}

func (q *Queries) DeleteMemoryNode(ctx context.Context, arg DeleteMemoryNodeParams) error {
	_, err := q.db.Exec(ctx, deleteMemoryNode, arg.BotID, arg.ID)
	return err
}

const getMemoryNode = `-- name: GetMemoryNode :one
SELECT id, bot_id, body, hash, layer, fact_type, subject, confidence, metadata, source_message_ids, profile_ref, topic, captured_at, expires_at, updated_at, created_at, team_id FROM memory_nodes
WHERE team_id = public.sophia_current_team_id() AND bot_id = $1 AND id = $2
`

type GetMemoryNodeParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	ID    string      `json:"id"`
}

func (q *Queries) GetMemoryNode(ctx context.Context, arg GetMemoryNodeParams) (MemoryNode, error) {
	row := q.db.QueryRow(ctx, getMemoryNode, arg.BotID, arg.ID)
	var i MemoryNode
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Body,
		&i.Hash,
		&i.Layer,
		&i.FactType,
		&i.Subject,
		&i.Confidence,
		&i.Metadata,
		&i.SourceMessageIds,
		&i.ProfileRef,
		&i.Topic,
		&i.CapturedAt,
		&i.ExpiresAt,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.TeamID,
	)
	return i, err
}

const insertMemoryEdge = `-- name: InsertMemoryEdge :exec
INSERT INTO memory_edges (bot_id, src_node, dst_node, rel, weight, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (team_id, bot_id, src_node, dst_node, rel) DO UPDATE SET
  weight = EXCLUDED.weight,
  metadata = EXCLUDED.metadata
`

type InsertMemoryEdgeParams struct {
	BotID    pgtype.UUID `json:"bot_id"`
	SrcNode  string      `json:"src_node"`
	DstNode  string      `json:"dst_node"`
	Rel      string      `json:"rel"`
	Weight   float32     `json:"weight"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) InsertMemoryEdge(ctx context.Context, arg InsertMemoryEdgeParams) error {
	_, err := q.db.Exec(ctx, insertMemoryEdge,
		arg.BotID,
		arg.SrcNode,
		arg.DstNode,
		arg.Rel,
		arg.Weight,
		arg.Metadata,
	)
	return err
}

const listMemoryEdgesByBot = `-- name: ListMemoryEdgesByBot :many
SELECT id, bot_id, src_node, dst_node, rel, weight, metadata, created_at, team_id FROM memory_edges
WHERE team_id = public.sophia_current_team_id() AND bot_id = $1
`

func (q *Queries) ListMemoryEdgesByBot(ctx context.Context, botID pgtype.UUID) ([]MemoryEdge, error) {
	rows, err := q.db.Query(ctx, listMemoryEdgesByBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryEdge
	for rows.Next() {
		var i MemoryEdge
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SrcNode,
			&i.DstNode,
			&i.Rel,
			&i.Weight,
			&i.Metadata,
			&i.CreatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryEdgesByRel = `-- name: ListMemoryEdgesByRel :many
SELECT id, bot_id, src_node, dst_node, rel, weight, metadata, created_at, team_id FROM memory_edges
WHERE team_id = public.sophia_current_team_id() AND bot_id = $1 AND rel = $2
`

type ListMemoryEdgesByRelParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	Rel   string      `json:"rel"`
}

func (q *Queries) ListMemoryEdgesByRel(ctx context.Context, arg ListMemoryEdgesByRelParams) ([]MemoryEdge, error) {
	rows, err := q.db.Query(ctx, listMemoryEdgesByRel, arg.BotID, arg.Rel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryEdge
	for rows.Next() {
		var i MemoryEdge
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SrcNode,
			&i.DstNode,
			&i.Rel,
			&i.Weight,
			&i.Metadata,
			&i.CreatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryEdgesFromNode = `-- name: ListMemoryEdgesFromNode :many
SELECT id, bot_id, src_node, dst_node, rel, weight, metadata, created_at, team_id FROM memory_edges
WHERE team_id = public.sophia_current_team_id() AND bot_id = $1 AND src_node = $2
ORDER BY weight DESC
`

type ListMemoryEdgesFromNodeParams struct {
	BotID   pgtype.UUID `json:"bot_id"`
	SrcNode string      `json:"src_node"`
}

func (q *Queries) ListMemoryEdgesFromNode(ctx context.Context, arg ListMemoryEdgesFromNodeParams) ([]MemoryEdge, error) {
	rows, err := q.db.Query(ctx, listMemoryEdgesFromNode, arg.BotID, arg.SrcNode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryEdge
	for rows.Next() {
		var i MemoryEdge
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SrcNode,
			&i.DstNode,
			&i.Rel,
			&i.Weight,
			&i.Metadata,
			&i.CreatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryNodesByBot = `-- name: ListMemoryNodesByBot :many
SELECT id, bot_id, body, hash, layer, fact_type, subject, confidence, metadata, source_message_ids, profile_ref, topic, captured_at, expires_at, updated_at, created_at, team_id FROM memory_nodes
WHERE team_id = public.sophia_current_team_id() AND bot_id = $1
ORDER BY captured_at ASC
`

func (q *Queries) ListMemoryNodesByBot(ctx context.Context, botID pgtype.UUID) ([]MemoryNode, error) {
	rows, err := q.db.Query(ctx, listMemoryNodesByBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryNode
	for rows.Next() {
		var i MemoryNode
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Body,
			&i.Hash,
			&i.Layer,
			&i.FactType,
			&i.Subject,
			&i.Confidence,
			&i.Metadata,
			&i.SourceMessageIds,
			&i.ProfileRef,
			&i.Topic,
			&i.CapturedAt,
			&i.ExpiresAt,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryNodesByBotLayer = `-- name: ListMemoryNodesByBotLayer :many
SELECT id, bot_id, body, hash, layer, fact_type, subject, confidence, metadata, source_message_ids, profile_ref, topic, captured_at, expires_at, updated_at, created_at, team_id FROM memory_nodes
WHERE team_id = public.sophia_current_team_id() AND bot_id = $1 AND layer = $2
ORDER BY captured_at ASC
`

type ListMemoryNodesByBotLayerParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	Layer string      `json:"layer"`
}

func (q *Queries) ListMemoryNodesByBotLayer(ctx context.Context, arg ListMemoryNodesByBotLayerParams) ([]MemoryNode, error) {
	rows, err := q.db.Query(ctx, listMemoryNodesByBotLayer, arg.BotID, arg.Layer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryNode
	for rows.Next() {
		var i MemoryNode
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Body,
			&i.Hash,
			&i.Layer,
			&i.FactType,
			&i.Subject,
			&i.Confidence,
			&i.Metadata,
			&i.SourceMessageIds,
			&i.ProfileRef,
			&i.Topic,
			&i.CapturedAt,
			&i.ExpiresAt,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryNodesByBotProfile = `-- name: ListMemoryNodesByBotProfile :many
SELECT id, bot_id, body, hash, layer, fact_type, subject, confidence, metadata, source_message_ids, profile_ref, topic, captured_at, expires_at, updated_at, created_at, team_id FROM memory_nodes
WHERE team_id = public.sophia_current_team_id() AND bot_id = $1 AND profile_ref = $2
ORDER BY captured_at ASC
`

type ListMemoryNodesByBotProfileParams struct {
	BotID      pgtype.UUID `json:"bot_id"`
	ProfileRef string      `json:"profile_ref"`
}

func (q *Queries) ListMemoryNodesByBotProfile(ctx context.Context, arg ListMemoryNodesByBotProfileParams) ([]MemoryNode, error) {
	rows, err := q.db.Query(ctx, listMemoryNodesByBotProfile, arg.BotID, arg.ProfileRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryNode
	for rows.Next() {
		var i MemoryNode
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Body,
			&i.Hash,
			&i.Layer,
			&i.FactType,
			&i.Subject,
			&i.Confidence,
			&i.Metadata,
			&i.SourceMessageIds,
			&i.ProfileRef,
			&i.Topic,
			&i.CapturedAt,
			&i.ExpiresAt,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMemoryNode = `-- name: UpsertMemoryNode :one
INSERT INTO memory_nodes (
  id, bot_id, body, hash, layer, fact_type, subject, confidence,
  metadata, source_message_ids, profile_ref, topic, captured_at, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (team_id, id) DO UPDATE SET
  body = EXCLUDED.body,
  hash = EXCLUDED.hash,
  layer = EXCLUDED.layer,
  fact_type = EXCLUDED.fact_type,
  subject = EXCLUDED.subject,
  confidence = EXCLUDED.confidence,
  metadata = EXCLUDED.metadata,
  source_message_ids = EXCLUDED.source_message_ids,
  profile_ref = EXCLUDED.profile_ref,
  topic = EXCLUDED.topic,
  expires_at = EXCLUDED.expires_at,
  updated_at = now()
RETURNING id, bot_id, body, hash, layer, fact_type, subject, confidence, metadata, source_message_ids, profile_ref, topic, captured_at, expires_at, updated_at, created_at, team_id
`

type UpsertMemoryNodeParams struct {
	ID               string             `json:"id"`
	BotID            pgtype.UUID        `json:"bot_id"`
	Body             string             `json:"body"`
	Hash             string             `json:"hash"`
	Layer            string             `json:"layer"`
	FactType         string             `json:"fact_type"`
	Subject          string             `json:"subject"`
	Confidence       float32            `json:"confidence"`
	Metadata         []byte             `json:"metadata"`
	SourceMessageIds []byte             `json:"source_message_ids"`
	ProfileRef       string             `json:"profile_ref"`
	Topic            string             `json:"topic"`
	CapturedAt       pgtype.Timestamptz `json:"captured_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertMemoryNode(ctx context.Context, arg UpsertMemoryNodeParams) (MemoryNode, error) {
	row := q.db.QueryRow(ctx, upsertMemoryNode,
		arg.ID,
		arg.BotID,
		arg.Body,
		arg.Hash,
		arg.Layer,
		arg.FactType,
		arg.Subject,
		arg.Confidence,
		arg.Metadata,
		arg.SourceMessageIds,
		arg.ProfileRef,
		arg.Topic,
		arg.CapturedAt,
		arg.ExpiresAt,
	)
	var i MemoryNode
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Body,
		&i.Hash,
		&i.Layer,
		&i.FactType,
		&i.Subject,
		&i.Confidence,
		&i.Metadata,
		&i.SourceMessageIds,
		&i.ProfileRef,
		&i.Topic,
		&i.CapturedAt,
		&i.ExpiresAt,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.TeamID,
	)
	return i, err
}
