// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireProviderTemplateSyncLock = `-- name: AcquireProviderTemplateSyncLock :exec
SELECT pg_advisory_xact_lock(78273144982731)
`

func (q *Queries) AcquireProviderTemplateSyncLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, acquireProviderTemplateSyncLock)
	return err
}

const getProviderTemplateByDomainAndKey = `-- name: GetProviderTemplateByDomainAndKey :one
SELECT id, key, domain, name, description, icon, driver, config_schema, default_config, metadata, source, content_hash, sort_order, active, created_at, updated_at
FROM template.provider_templates
WHERE domain = $1 AND key = $2
`

type GetProviderTemplateByDomainAndKeyParams struct {
	Domain string `json:"domain"`
	Key    string `json:"key"`
}

func (q *Queries) GetProviderTemplateByDomainAndKey(ctx context.Context, arg GetProviderTemplateByDomainAndKeyParams) (TemplateProviderTemplate, error) {
	row := q.db.QueryRow(ctx, getProviderTemplateByDomainAndKey, arg.Domain, arg.Key)
	var i TemplateProviderTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Domain,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Driver,
		&i.ConfigSchema,
		&i.DefaultConfig,
		&i.Metadata,
		&i.Source,
		&i.ContentHash,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderTemplateByID = `-- name: GetProviderTemplateByID :one
SELECT id, key, domain, name, description, icon, driver, config_schema, default_config, metadata, source, content_hash, sort_order, active, created_at, updated_at
FROM template.provider_templates
WHERE id = $1 AND active = true
`

func (q *Queries) GetProviderTemplateByID(ctx context.Context, id pgtype.UUID) (TemplateProviderTemplate, error) {
	row := q.db.QueryRow(ctx, getProviderTemplateByID, id)
	var i TemplateProviderTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Domain,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Driver,
		&i.ConfigSchema,
		&i.DefaultConfig,
		&i.Metadata,
		&i.Source,
		&i.ContentHash,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllProviderTemplateModels = `-- name: ListAllProviderTemplateModels :many
SELECT id, provider_template_id, model_id, name, type, config, metadata, sort_order, active, created_at, updated_at
FROM template.provider_template_models
WHERE provider_template_id = $1
ORDER BY sort_order ASC, model_id ASC
`

func (q *Queries) ListAllProviderTemplateModels(ctx context.Context, providerTemplateID pgtype.UUID) ([]TemplateProviderTemplateModel, error) {
	rows, err := q.db.Query(ctx, listAllProviderTemplateModels, providerTemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateProviderTemplateModel
	for rows.Next() {
		var i TemplateProviderTemplateModel
		if err := rows.Scan(
			&i.ID,
			&i.ProviderTemplateID,
			&i.ModelID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.Metadata,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProviderTemplates = `-- name: ListAllProviderTemplates :many
SELECT id, key, domain, name, description, icon, driver, config_schema, default_config, metadata, source, content_hash, sort_order, active, created_at, updated_at
FROM template.provider_templates
ORDER BY domain ASC, sort_order ASC, key ASC
`

func (q *Queries) ListAllProviderTemplates(ctx context.Context) ([]TemplateProviderTemplate, error) {
	rows, err := q.db.Query(ctx, listAllProviderTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateProviderTemplate
	for rows.Next() {
		var i TemplateProviderTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Domain,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Driver,
			&i.ConfigSchema,
			&i.DefaultConfig,
			&i.Metadata,
			&i.Source,
			&i.ContentHash,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderTemplateModels = `-- name: ListProviderTemplateModels :many
SELECT id, provider_template_id, model_id, name, type, config, metadata, sort_order, active, created_at, updated_at
FROM template.provider_template_models
WHERE provider_template_id = $1
  AND active = true
ORDER BY sort_order ASC, model_id ASC
`

func (q *Queries) ListProviderTemplateModels(ctx context.Context, providerTemplateID pgtype.UUID) ([]TemplateProviderTemplateModel, error) {
	rows, err := q.db.Query(ctx, listProviderTemplateModels, providerTemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateProviderTemplateModel
	for rows.Next() {
		var i TemplateProviderTemplateModel
		if err := rows.Scan(
			&i.ID,
			&i.ProviderTemplateID,
			&i.ModelID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.Metadata,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderTemplates = `-- name: ListProviderTemplates :many
SELECT
  t.id, t.key, t.domain, t.name, t.description, t.icon, t.driver, t.config_schema, t.default_config, t.metadata, t.source, t.content_hash, t.sort_order, t.active, t.created_at, t.updated_at,
  EXISTS (
    SELECT 1 FROM public.providers p
     WHERE p.team_id = public.sophia_current_team_id()
       AND (
         p.provider_template_id = t.id
         OR p.metadata->'template'->>'id' = t.id::text
         OR (
           t.source <> ''
           AND (
             p.metadata->'preset'->>'source' = t.source
             OR p.metadata->'registry'->>'source' = t.source
           )
         )
       )
  ) AS configured
FROM template.provider_templates t
WHERE t.active = true
  AND ($1::text = '' OR t.domain = $1)
ORDER BY t.sort_order ASC, t.name ASC, t.key ASC
`

type ListProviderTemplatesRow struct {
	ID            pgtype.UUID        `json:"id"`
	Key           string             `json:"key"`
	Domain        string             `json:"domain"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Icon          pgtype.Text        `json:"icon"`
	Driver        string             `json:"driver"`
	ConfigSchema  []byte             `json:"config_schema"`
	DefaultConfig []byte             `json:"default_config"`
	Metadata      []byte             `json:"metadata"`
	Source        string             `json:"source"`
	ContentHash   string             `json:"content_hash"`
	SortOrder     int32              `json:"sort_order"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Configured    bool               `json:"configured"`
}

func (q *Queries) ListProviderTemplates(ctx context.Context, domain string) ([]ListProviderTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listProviderTemplates, domain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProviderTemplatesRow
	for rows.Next() {
		var i ListProviderTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Domain,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Driver,
			&i.ConfigSchema,
			&i.DefaultConfig,
			&i.Metadata,
			&i.Source,
			&i.ContentHash,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Configured,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProviderTemplateActive = `-- name: SetProviderTemplateActive :exec
UPDATE template.provider_templates
SET active = $1, updated_at = now()
WHERE id = $2 AND active IS DISTINCT FROM $1
`

type SetProviderTemplateActiveParams struct {
	Active bool        `json:"active"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) SetProviderTemplateActive(ctx context.Context, arg SetProviderTemplateActiveParams) error {
	_, err := q.db.Exec(ctx, setProviderTemplateActive, arg.Active, arg.ID)
	return err
}

const setProviderTemplateModelActive = `-- name: SetProviderTemplateModelActive :exec
UPDATE template.provider_template_models
SET active = $1, updated_at = now()
WHERE id = $2 AND active IS DISTINCT FROM $1
`

type SetProviderTemplateModelActiveParams struct {
	Active bool        `json:"active"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) SetProviderTemplateModelActive(ctx context.Context, arg SetProviderTemplateModelActiveParams) error {
	_, err := q.db.Exec(ctx, setProviderTemplateModelActive, arg.Active, arg.ID)
	return err
}

const upsertProviderTemplate = `-- name: UpsertProviderTemplate :one
INSERT INTO template.provider_templates (
  key,
  domain,
  name,
  description,
  icon,
  driver,
  config_schema,
  default_config,
  metadata,
  source,
  content_hash,
  sort_order,
  active
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  true
)
ON CONFLICT (domain, key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  driver = EXCLUDED.driver,
  config_schema = EXCLUDED.config_schema,
  default_config = EXCLUDED.default_config,
  metadata = EXCLUDED.metadata,
  source = EXCLUDED.source,
  content_hash = EXCLUDED.content_hash,
  sort_order = EXCLUDED.sort_order,
  active = true,
  updated_at = now()
RETURNING id, key, domain, name, description, icon, driver, config_schema, default_config, metadata, source, content_hash, sort_order, active, created_at, updated_at
`

type UpsertProviderTemplateParams struct {
	Key           string      `json:"key"`
	Domain        string      `json:"domain"`
	Name          string      `json:"name"`
	Description   string      `json:"description"`
	Icon          pgtype.Text `json:"icon"`
	Driver        string      `json:"driver"`
	ConfigSchema  []byte      `json:"config_schema"`
	DefaultConfig []byte      `json:"default_config"`
	Metadata      []byte      `json:"metadata"`
	Source        string      `json:"source"`
	ContentHash   string      `json:"content_hash"`
	SortOrder     int32       `json:"sort_order"`
}

func (q *Queries) UpsertProviderTemplate(ctx context.Context, arg UpsertProviderTemplateParams) (TemplateProviderTemplate, error) {
	row := q.db.QueryRow(ctx, upsertProviderTemplate,
		arg.Key,
		arg.Domain,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Driver,
		arg.ConfigSchema,
		arg.DefaultConfig,
		arg.Metadata,
		arg.Source,
		arg.ContentHash,
		arg.SortOrder,
	)
	var i TemplateProviderTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Domain,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Driver,
		&i.ConfigSchema,
		&i.DefaultConfig,
		&i.Metadata,
		&i.Source,
		&i.ContentHash,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProviderTemplateModel = `-- name: UpsertProviderTemplateModel :one
INSERT INTO template.provider_template_models (
  provider_template_id,
  model_id,
  name,
  type,
  config,
  metadata,
  sort_order,
  active
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  true
)
ON CONFLICT (provider_template_id, type, model_id) DO UPDATE SET
  name = EXCLUDED.name,
  config = EXCLUDED.config,
  metadata = EXCLUDED.metadata,
  sort_order = EXCLUDED.sort_order,
  active = true,
  updated_at = now()
RETURNING id, provider_template_id, model_id, name, type, config, metadata, sort_order, active, created_at, updated_at
`

type UpsertProviderTemplateModelParams struct {
	ProviderTemplateID pgtype.UUID `json:"provider_template_id"`
	ModelID            string      `json:"model_id"`
	Name               string      `json:"name"`
	Type               string      `json:"type"`
	Config             []byte      `json:"config"`
	Metadata           []byte      `json:"metadata"`
	SortOrder          int32       `json:"sort_order"`
}

func (q *Queries) UpsertProviderTemplateModel(ctx context.Context, arg UpsertProviderTemplateModelParams) (TemplateProviderTemplateModel, error) {
	row := q.db.QueryRow(ctx, upsertProviderTemplateModel,
		arg.ProviderTemplateID,
		arg.ModelID,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.Metadata,
		arg.SortOrder,
	)
	var i TemplateProviderTemplateModel
	err := row.Scan(
		&i.ID,
		&i.ProviderTemplateID,
		&i.ModelID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Metadata,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
