// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateSessionRuntimeFence = `-- name: ActivateSessionRuntimeFence :one
UPDATE bot_sessions
SET runtime_fencing_token = $1
WHERE team_id = public.sophia_current_team_id()
  AND id = $2
  AND bot_id = $3
  AND runtime_fencing_token <= $1
  AND deleted_at IS NULL
RETURNING runtime_fencing_token
`

type ActivateSessionRuntimeFenceParams struct {
	RuntimeFencingToken int64       `json:"runtime_fencing_token"`
	SessionID           pgtype.UUID `json:"session_id"`
	BotID               pgtype.UUID `json:"bot_id"`
}

func (q *Queries) ActivateSessionRuntimeFence(ctx context.Context, arg ActivateSessionRuntimeFenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, activateSessionRuntimeFence, arg.RuntimeFencingToken, arg.SessionID, arg.BotID)
	var runtime_fencing_token int64
	err := row.Scan(&runtime_fencing_token)
	return runtime_fencing_token, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO bot_sessions (
  bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, parent_session_id, created_by_user_id
)
VALUES (
  $1,
  $2::uuid,
  $3::text,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10::uuid,
  $11::uuid
)
RETURNING id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, compaction_epoch, runtime_fencing_token, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at, team_id
`

type CreateSessionParams struct {
	BotID           pgtype.UUID `json:"bot_id"`
	RouteID         pgtype.UUID `json:"route_id"`
	ChannelType     pgtype.Text `json:"channel_type"`
	Type            string      `json:"type"`
	SessionMode     string      `json:"session_mode"`
	RuntimeType     string      `json:"runtime_type"`
	RuntimeMetadata []byte      `json:"runtime_metadata"`
	Title           string      `json:"title"`
	Metadata        []byte      `json:"metadata"`
	ParentSessionID pgtype.UUID `json:"parent_session_id"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (BotSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.BotID,
		arg.RouteID,
		arg.ChannelType,
		arg.Type,
		arg.SessionMode,
		arg.RuntimeType,
		arg.RuntimeMetadata,
		arg.Title,
		arg.Metadata,
		arg.ParentSessionID,
		arg.CreatedByUserID,
	)
	var i BotSession
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RouteID,
		&i.ChannelType,
		&i.Type,
		&i.SessionMode,
		&i.RuntimeType,
		&i.RuntimeMetadata,
		&i.Title,
		&i.Metadata,
		&i.NextTurnPosition,
		&i.CompactionEpoch,
		&i.RuntimeFencingToken,
		&i.ParentSessionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
	)
	return i, err
}

const deleteSessionDiscussCursorsByBot = `-- name: DeleteSessionDiscussCursorsByBot :exec
DELETE FROM bot_session_discuss_cursors
WHERE team_id = public.sophia_current_team_id()
  AND session_id IN (
  SELECT id
  FROM bot_sessions
  WHERE team_id = public.sophia_current_team_id()
    AND bot_id = $1
)
`

func (q *Queries) DeleteSessionDiscussCursorsByBot(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionDiscussCursorsByBot, botID)
	return err
}

const forkSessionFromAssistantMessage = `-- name: ForkSessionFromAssistantMessage :one
WITH source_session AS (
  SELECT s.id, s.bot_id, s.route_id, s.channel_type, s.type, s.session_mode, s.runtime_type, s.runtime_metadata, s.title, s.metadata, s.next_turn_position, s.compaction_epoch, s.runtime_fencing_token, s.parent_session_id, s.created_by_user_id, s.created_at, s.updated_at, s.deleted_at, s.team_id
  FROM bot_sessions s
  WHERE s.team_id = public.sophia_current_team_id()
    AND s.id = $1
    AND s.bot_id = $2
    AND s.type = 'chat'
    AND s.deleted_at IS NULL
),
target_turn AS (
  SELECT
    vm.turn_id AS id,
    vm.turn_position AS position,
    vm.id AS message_id
  FROM source_session s
  JOIN bot_visible_history_messages vm ON vm.team_id = public.sophia_current_team_id()
    AND vm.session_id = s.id
    AND vm.id = $3
    AND vm.role = 'assistant'
    AND vm.turn_id IS NOT NULL
    AND vm.turn_position IS NOT NULL
  LIMIT 1
),
copy_messages AS (
  SELECT
    vm.id AS old_message_id,
    gen_random_uuid() AS new_message_id,
    vm.sender_channel_identity_id,
    vm.sender_account_user_id,
    vm.source_message_id,
    vm.source_reply_to_message_id,
    vm.role,
    vm.content,
    vm.metadata,
    vm.usage,
    vm.session_mode,
    vm.runtime_type,
    vm.model_id,
    vm.display_text,
    vm.turn_id AS old_turn_id,
    vm.turn_position,
    vm.turn_message_seq,
    vm.created_at
  FROM bot_visible_history_messages vm
  JOIN target_turn tt ON (
    vm.turn_position < tt.position
    OR vm.turn_position = tt.position
  )
  WHERE vm.team_id = public.sophia_current_team_id()
    AND vm.session_id = $1
  ORDER BY vm.turn_position ASC, vm.turn_message_seq ASC, vm.created_at ASC, vm.id ASC
),
copy_turns AS (
  SELECT
    cm.old_turn_id,
    gen_random_uuid() AS new_turn_id,
    cm.turn_position AS old_position,
    ROW_NUMBER() OVER (ORDER BY cm.turn_position ASC)::bigint AS new_position
  FROM (
    SELECT DISTINCT old_turn_id, turn_position
    FROM copy_messages
  ) cm
  ORDER BY cm.turn_position ASC
),
next_turn_position AS (
  SELECT COALESCE(MAX(new_position), 0) + 1 AS value
  FROM copy_turns
),
fork_anchor_message AS (
  SELECT assistant_message.new_message_id
  FROM target_turn tt
  JOIN copy_messages assistant_message ON assistant_message.old_message_id = tt.message_id
  LIMIT 1
),
prepared_metadata AS (
  SELECT COALESCE($4::jsonb, '{}'::jsonb) AS value
),
fork_plan AS (
  SELECT
    s.id, s.bot_id, s.route_id, s.channel_type, s.type, s.session_mode, s.runtime_type, s.runtime_metadata, s.title, s.metadata, s.next_turn_position, s.compaction_epoch, s.runtime_fencing_token, s.parent_session_id, s.created_by_user_id, s.created_at, s.updated_at, s.deleted_at, s.team_id,
    fam.new_message_id AS fork_message_id,
    ntp.value AS next_turn_position_value
  FROM source_session s
  JOIN fork_anchor_message fam ON true
  CROSS JOIN next_turn_position ntp
  WHERE EXISTS (SELECT 1 FROM copy_turns)
),
created_session AS (
  INSERT INTO bot_sessions (
    bot_id,
    channel_type,
    type,
    session_mode,
    runtime_type,
    runtime_metadata,
    title,
    metadata,
    next_turn_position,
    created_by_user_id
  )
  SELECT
    fp.bot_id,
    fp.channel_type,
    fp.type,
    fp.session_mode,
    fp.runtime_type,
    fp.runtime_metadata,
    $5,
    jsonb_set(
      pm.value,
      '{forked_from}',
      COALESCE(pm.value->'forked_from', '{}'::jsonb) || jsonb_build_object('fork_message_id', fp.fork_message_id::text),
      true
    ),
    fp.next_turn_position_value,
    $6::uuid
  FROM fork_plan fp
  CROSS JOIN prepared_metadata pm
  RETURNING id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, compaction_epoch, runtime_fencing_token, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at, team_id
),
inserted_messages AS (
  INSERT INTO bot_history_messages (
    id,
    bot_id,
    session_id,
    sender_channel_identity_id,
    sender_account_user_id,
    source_message_id,
    source_reply_to_message_id,
    role,
    content,
    metadata,
    usage,
    session_mode,
    runtime_type,
    model_id,
    display_text,
    turn_id,
    turn_position,
    turn_message_seq,
    turn_visible,
    created_at
  )
  SELECT
    cm.new_message_id,
    cs.bot_id,
    cs.id,
    cm.sender_channel_identity_id,
    cm.sender_account_user_id,
    cm.source_message_id,
    cm.source_reply_to_message_id,
    cm.role,
    cm.content,
    cm.metadata,
    cm.usage,
    cm.session_mode,
    cm.runtime_type,
    cm.model_id,
    cm.display_text,
    ct.new_turn_id,
    ct.new_position,
    cm.turn_message_seq,
    true,
    cm.created_at
  FROM copy_messages cm
  JOIN copy_turns ct ON ct.old_turn_id = cm.old_turn_id
  CROSS JOIN created_session cs
  RETURNING id
),
copied_assets AS (
  INSERT INTO bot_history_message_assets (
    message_id,
    role,
    ordinal,
    content_hash,
    mime,
    size_bytes,
    storage_key,
    name,
    metadata
  )
  SELECT
    cm.new_message_id,
    a.role,
    a.ordinal,
    a.content_hash,
    a.mime,
    a.size_bytes,
    a.storage_key,
    a.name,
    a.metadata
  FROM bot_history_message_assets a
  JOIN copy_messages cm ON cm.old_message_id = a.message_id
  JOIN inserted_messages im ON im.id = cm.new_message_id
  WHERE a.team_id = public.sophia_current_team_id()
  RETURNING id
)
SELECT cs.id, cs.bot_id, cs.route_id, cs.channel_type, cs.type, cs.session_mode, cs.runtime_type, cs.runtime_metadata, cs.title, cs.metadata, cs.next_turn_position, cs.compaction_epoch, cs.runtime_fencing_token, cs.parent_session_id, cs.created_by_user_id, cs.created_at, cs.updated_at, cs.deleted_at, cs.team_id
FROM created_session cs
CROSS JOIN (SELECT count(*) AS copied_asset_count FROM copied_assets) copied_asset_counts
`

type ForkSessionFromAssistantMessageParams struct {
	SessionID       pgtype.UUID `json:"session_id"`
	BotID           pgtype.UUID `json:"bot_id"`
	MessageID       pgtype.UUID `json:"message_id"`
	Metadata        []byte      `json:"metadata"`
	Title           string      `json:"title"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
}

type ForkSessionFromAssistantMessageRow struct {
	ID                  pgtype.UUID        `json:"id"`
	BotID               pgtype.UUID        `json:"bot_id"`
	RouteID             pgtype.UUID        `json:"route_id"`
	ChannelType         pgtype.Text        `json:"channel_type"`
	Type                string             `json:"type"`
	SessionMode         string             `json:"session_mode"`
	RuntimeType         string             `json:"runtime_type"`
	RuntimeMetadata     []byte             `json:"runtime_metadata"`
	Title               string             `json:"title"`
	Metadata            []byte             `json:"metadata"`
	NextTurnPosition    int64              `json:"next_turn_position"`
	CompactionEpoch     int64              `json:"compaction_epoch"`
	RuntimeFencingToken int64              `json:"runtime_fencing_token"`
	ParentSessionID     pgtype.UUID        `json:"parent_session_id"`
	CreatedByUserID     pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	TeamID              pgtype.UUID        `json:"team_id"`
}

func (q *Queries) ForkSessionFromAssistantMessage(ctx context.Context, arg ForkSessionFromAssistantMessageParams) (ForkSessionFromAssistantMessageRow, error) {
	row := q.db.QueryRow(ctx, forkSessionFromAssistantMessage,
		arg.SessionID,
		arg.BotID,
		arg.MessageID,
		arg.Metadata,
		arg.Title,
		arg.CreatedByUserID,
	)
	var i ForkSessionFromAssistantMessageRow
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RouteID,
		&i.ChannelType,
		&i.Type,
		&i.SessionMode,
		&i.RuntimeType,
		&i.RuntimeMetadata,
		&i.Title,
		&i.Metadata,
		&i.NextTurnPosition,
		&i.CompactionEpoch,
		&i.RuntimeFencingToken,
		&i.ParentSessionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, compaction_epoch, runtime_fencing_token, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at, team_id
FROM bot_sessions
WHERE team_id = public.sophia_current_team_id()
  AND id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (BotSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i BotSession
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RouteID,
		&i.ChannelType,
		&i.Type,
		&i.SessionMode,
		&i.RuntimeType,
		&i.RuntimeMetadata,
		&i.Title,
		&i.Metadata,
		&i.NextTurnPosition,
		&i.CompactionEpoch,
		&i.RuntimeFencingToken,
		&i.ParentSessionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
	)
	return i, err
}

const getSessionDiscussCursor = `-- name: GetSessionDiscussCursor :one
SELECT session_id, scope_key, route_id, source, consumed_cursor, consumed_event_cursor, updated_at, team_id
FROM bot_session_discuss_cursors
WHERE team_id = public.sophia_current_team_id()
  AND session_id = $1
  AND scope_key = $2
`

type GetSessionDiscussCursorParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	ScopeKey  string      `json:"scope_key"`
}

func (q *Queries) GetSessionDiscussCursor(ctx context.Context, arg GetSessionDiscussCursorParams) (BotSessionDiscussCursor, error) {
	row := q.db.QueryRow(ctx, getSessionDiscussCursor, arg.SessionID, arg.ScopeKey)
	var i BotSessionDiscussCursor
	err := row.Scan(
		&i.SessionID,
		&i.ScopeKey,
		&i.RouteID,
		&i.Source,
		&i.ConsumedCursor,
		&i.ConsumedEventCursor,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const listSessionDiscussCursorsByBot = `-- name: ListSessionDiscussCursorsByBot :many
SELECT c.session_id, c.scope_key, c.route_id, c.source, c.consumed_cursor, c.consumed_event_cursor, c.updated_at, c.team_id
FROM bot_session_discuss_cursors c
JOIN bot_sessions s ON s.id = c.session_id
WHERE c.team_id = public.sophia_current_team_id()
  AND s.team_id = public.sophia_current_team_id()
  AND s.bot_id = $1
ORDER BY c.updated_at ASC, c.session_id ASC, c.scope_key ASC
`

func (q *Queries) ListSessionDiscussCursorsByBot(ctx context.Context, botID pgtype.UUID) ([]BotSessionDiscussCursor, error) {
	rows, err := q.db.Query(ctx, listSessionDiscussCursorsByBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSessionDiscussCursor
	for rows.Next() {
		var i BotSessionDiscussCursor
		if err := rows.Scan(
			&i.SessionID,
			&i.ScopeKey,
			&i.RouteID,
			&i.Source,
			&i.ConsumedCursor,
			&i.ConsumedEventCursor,
			&i.UpdatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByBot = `-- name: ListSessionsByBot :many
SELECT
  s.id, s.bot_id, s.route_id, s.channel_type, s.type, s.session_mode, s.runtime_type, s.runtime_metadata, s.title, s.metadata,
  s.parent_session_id, s.created_by_user_id, s.created_at, s.updated_at, s.deleted_at
FROM bot_sessions s
WHERE s.team_id = public.sophia_current_team_id()
  AND s.bot_id = $1
  AND s.deleted_at IS NULL
ORDER BY s.updated_at DESC
`

type ListSessionsByBotRow struct {
	ID              pgtype.UUID        `json:"id"`
	BotID           pgtype.UUID        `json:"bot_id"`
	RouteID         pgtype.UUID        `json:"route_id"`
	ChannelType     pgtype.Text        `json:"channel_type"`
	Type            string             `json:"type"`
	SessionMode     string             `json:"session_mode"`
	RuntimeType     string             `json:"runtime_type"`
	RuntimeMetadata []byte             `json:"runtime_metadata"`
	Title           string             `json:"title"`
	Metadata        []byte             `json:"metadata"`
	ParentSessionID pgtype.UUID        `json:"parent_session_id"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListSessionsByBot(ctx context.Context, botID pgtype.UUID) ([]ListSessionsByBotRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByBotRow
	for rows.Next() {
		var i ListSessionsByBotRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.RouteID,
			&i.ChannelType,
			&i.Type,
			&i.SessionMode,
			&i.RuntimeType,
			&i.RuntimeMetadata,
			&i.Title,
			&i.Metadata,
			&i.ParentSessionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByBotAndCreatedByUser = `-- name: ListSessionsByBotAndCreatedByUser :many
SELECT
  s.id, s.bot_id, s.route_id, s.channel_type, s.type, s.session_mode, s.runtime_type, s.runtime_metadata, s.title, s.metadata,
  s.parent_session_id, s.created_by_user_id, s.created_at, s.updated_at, s.deleted_at
FROM bot_sessions s
WHERE s.team_id = public.sophia_current_team_id()
  AND s.bot_id = $1
  AND s.created_by_user_id = $2
  AND s.deleted_at IS NULL
ORDER BY s.updated_at DESC
`

type ListSessionsByBotAndCreatedByUserParams struct {
	BotID           pgtype.UUID `json:"bot_id"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
}

type ListSessionsByBotAndCreatedByUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	BotID           pgtype.UUID        `json:"bot_id"`
	RouteID         pgtype.UUID        `json:"route_id"`
	ChannelType     pgtype.Text        `json:"channel_type"`
	Type            string             `json:"type"`
	SessionMode     string             `json:"session_mode"`
	RuntimeType     string             `json:"runtime_type"`
	RuntimeMetadata []byte             `json:"runtime_metadata"`
	Title           string             `json:"title"`
	Metadata        []byte             `json:"metadata"`
	ParentSessionID pgtype.UUID        `json:"parent_session_id"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListSessionsByBotAndCreatedByUser(ctx context.Context, arg ListSessionsByBotAndCreatedByUserParams) ([]ListSessionsByBotAndCreatedByUserRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByBotAndCreatedByUser, arg.BotID, arg.CreatedByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByBotAndCreatedByUserRow
	for rows.Next() {
		var i ListSessionsByBotAndCreatedByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.RouteID,
			&i.ChannelType,
			&i.Type,
			&i.SessionMode,
			&i.RuntimeType,
			&i.RuntimeMetadata,
			&i.Title,
			&i.Metadata,
			&i.ParentSessionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByBotAndCreatedByUserPaged = `-- name: ListSessionsByBotAndCreatedByUserPaged :many
SELECT
  s.id, s.bot_id, s.route_id, s.channel_type, s.type, s.session_mode, s.runtime_type, s.runtime_metadata, s.title, s.metadata,
  s.parent_session_id, s.created_by_user_id, s.created_at, s.updated_at, s.deleted_at
FROM bot_sessions s
WHERE s.team_id = public.sophia_current_team_id()
  AND s.bot_id = $1
  AND s.created_by_user_id = $2
  AND s.deleted_at IS NULL
  AND s.type = ANY($3::text[])
  AND (
    NOT $4::bool
    OR s.parent_session_id = $5::uuid
  )
  AND (
    NOT $6::bool
    OR (s.updated_at, s.id) < ($7::timestamptz, $8::uuid)
  )
ORDER BY s.updated_at DESC, s.id DESC
LIMIT $9::int
`

type ListSessionsByBotAndCreatedByUserPagedParams struct {
	BotID            pgtype.UUID        `json:"bot_id"`
	CreatedByUserID  pgtype.UUID        `json:"created_by_user_id"`
	Types            []string           `json:"types"`
	UseParentSession bool               `json:"use_parent_session"`
	ParentSessionID  pgtype.UUID        `json:"parent_session_id"`
	UseCursor        bool               `json:"use_cursor"`
	CursorUpdatedAt  pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID         pgtype.UUID        `json:"cursor_id"`
	LimitCount       int32              `json:"limit_count"`
}

type ListSessionsByBotAndCreatedByUserPagedRow struct {
	ID              pgtype.UUID        `json:"id"`
	BotID           pgtype.UUID        `json:"bot_id"`
	RouteID         pgtype.UUID        `json:"route_id"`
	ChannelType     pgtype.Text        `json:"channel_type"`
	Type            string             `json:"type"`
	SessionMode     string             `json:"session_mode"`
	RuntimeType     string             `json:"runtime_type"`
	RuntimeMetadata []byte             `json:"runtime_metadata"`
	Title           string             `json:"title"`
	Metadata        []byte             `json:"metadata"`
	ParentSessionID pgtype.UUID        `json:"parent_session_id"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListSessionsByBotAndCreatedByUserPaged(ctx context.Context, arg ListSessionsByBotAndCreatedByUserPagedParams) ([]ListSessionsByBotAndCreatedByUserPagedRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByBotAndCreatedByUserPaged,
		arg.BotID,
		arg.CreatedByUserID,
		arg.Types,
		arg.UseParentSession,
		arg.ParentSessionID,
		arg.UseCursor,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByBotAndCreatedByUserPagedRow
	for rows.Next() {
		var i ListSessionsByBotAndCreatedByUserPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.RouteID,
			&i.ChannelType,
			&i.Type,
			&i.SessionMode,
			&i.RuntimeType,
			&i.RuntimeMetadata,
			&i.Title,
			&i.Metadata,
			&i.ParentSessionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByBotPaged = `-- name: ListSessionsByBotPaged :many
SELECT
  s.id, s.bot_id, s.route_id, s.channel_type, s.type, s.session_mode, s.runtime_type, s.runtime_metadata, s.title, s.metadata,
  s.parent_session_id, s.created_by_user_id, s.created_at, s.updated_at, s.deleted_at
FROM bot_sessions s
WHERE s.team_id = public.sophia_current_team_id()
  AND s.bot_id = $1
  AND s.deleted_at IS NULL
  AND s.type = ANY($2::text[])
  AND (
    NOT $3::bool
    OR s.parent_session_id = $4::uuid
  )
  AND (
    NOT $5::bool
    OR (s.updated_at, s.id) < ($6::timestamptz, $7::uuid)
  )
ORDER BY s.updated_at DESC, s.id DESC
LIMIT $8::int
`

type ListSessionsByBotPagedParams struct {
	BotID            pgtype.UUID        `json:"bot_id"`
	Types            []string           `json:"types"`
	UseParentSession bool               `json:"use_parent_session"`
	ParentSessionID  pgtype.UUID        `json:"parent_session_id"`
	UseCursor        bool               `json:"use_cursor"`
	CursorUpdatedAt  pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID         pgtype.UUID        `json:"cursor_id"`
	LimitCount       int32              `json:"limit_count"`
}

type ListSessionsByBotPagedRow struct {
	ID              pgtype.UUID        `json:"id"`
	BotID           pgtype.UUID        `json:"bot_id"`
	RouteID         pgtype.UUID        `json:"route_id"`
	ChannelType     pgtype.Text        `json:"channel_type"`
	Type            string             `json:"type"`
	SessionMode     string             `json:"session_mode"`
	RuntimeType     string             `json:"runtime_type"`
	RuntimeMetadata []byte             `json:"runtime_metadata"`
	Title           string             `json:"title"`
	Metadata        []byte             `json:"metadata"`
	ParentSessionID pgtype.UUID        `json:"parent_session_id"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

// Cursor uses (updated_at, id) so pages stay stable when many rows share an
// updated_at. Callers always pass an explicit types filter; to opt out of
// filtering, pass every known type.
func (q *Queries) ListSessionsByBotPaged(ctx context.Context, arg ListSessionsByBotPagedParams) ([]ListSessionsByBotPagedRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByBotPaged,
		arg.BotID,
		arg.Types,
		arg.UseParentSession,
		arg.ParentSessionID,
		arg.UseCursor,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByBotPagedRow
	for rows.Next() {
		var i ListSessionsByBotPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.RouteID,
			&i.ChannelType,
			&i.Type,
			&i.SessionMode,
			&i.RuntimeType,
			&i.RuntimeMetadata,
			&i.Title,
			&i.Metadata,
			&i.ParentSessionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByRoute = `-- name: ListSessionsByRoute :many
SELECT id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, compaction_epoch, runtime_fencing_token, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at, team_id
FROM bot_sessions
WHERE team_id = public.sophia_current_team_id()
  AND route_id = $1
  AND deleted_at IS NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListSessionsByRoute(ctx context.Context, routeID pgtype.UUID) ([]BotSession, error) {
	rows, err := q.db.Query(ctx, listSessionsByRoute, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSession
	for rows.Next() {
		var i BotSession
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.RouteID,
			&i.ChannelType,
			&i.Type,
			&i.SessionMode,
			&i.RuntimeType,
			&i.RuntimeMetadata,
			&i.Title,
			&i.Metadata,
			&i.NextTurnPosition,
			&i.CompactionEpoch,
			&i.RuntimeFencingToken,
			&i.ParentSessionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubagentSessionsByParent = `-- name: ListSubagentSessionsByParent :many
SELECT id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, compaction_epoch, runtime_fencing_token, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at, team_id
FROM bot_sessions
WHERE team_id = public.sophia_current_team_id()
  AND parent_session_id = $1
  AND type = 'subagent'
  AND deleted_at IS NULL
  AND EXISTS (
    SELECT 1
    FROM subagent_configs config
    WHERE config.team_id = public.sophia_current_team_id()
      AND config.session_id = bot_sessions.id
  )
ORDER BY created_at DESC
`

func (q *Queries) ListSubagentSessionsByParent(ctx context.Context, parentSessionID pgtype.UUID) ([]BotSession, error) {
	rows, err := q.db.Query(ctx, listSubagentSessionsByParent, parentSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSession
	for rows.Next() {
		var i BotSession
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.RouteID,
			&i.ChannelType,
			&i.Type,
			&i.SessionMode,
			&i.RuntimeType,
			&i.RuntimeMetadata,
			&i.Title,
			&i.Metadata,
			&i.NextTurnPosition,
			&i.CompactionEpoch,
			&i.RuntimeFencingToken,
			&i.ParentSessionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSessionDecisionSequence = `-- name: LockSessionDecisionSequence :one
SELECT id
FROM bot_sessions
WHERE team_id = public.sophia_current_team_id()
  AND id = $1
  AND bot_id = $2
  AND deleted_at IS NULL
FOR UPDATE
`

type LockSessionDecisionSequenceParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	BotID     pgtype.UUID `json:"bot_id"`
}

func (q *Queries) LockSessionDecisionSequence(ctx context.Context, arg LockSessionDecisionSequenceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockSessionDecisionSequence, arg.SessionID, arg.BotID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const lockSessionRuntimeFence = `-- name: LockSessionRuntimeFence :one
SELECT runtime_fencing_token
FROM bot_sessions
WHERE team_id = public.sophia_current_team_id()
  AND id = $1
  AND bot_id = $2
  AND runtime_fencing_token = $3
  AND deleted_at IS NULL
FOR NO KEY UPDATE
`

type LockSessionRuntimeFenceParams struct {
	SessionID           pgtype.UUID `json:"session_id"`
	BotID               pgtype.UUID `json:"bot_id"`
	RuntimeFencingToken int64       `json:"runtime_fencing_token"`
}

func (q *Queries) LockSessionRuntimeFence(ctx context.Context, arg LockSessionRuntimeFenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockSessionRuntimeFence, arg.SessionID, arg.BotID, arg.RuntimeFencingToken)
	var runtime_fencing_token int64
	err := row.Scan(&runtime_fencing_token)
	return runtime_fencing_token, err
}

const lockSessionRuntimeFenceForActivation = `-- name: LockSessionRuntimeFenceForActivation :one
SELECT runtime_fencing_token
FROM bot_sessions
WHERE team_id = public.sophia_current_team_id()
  AND id = $1
  AND bot_id = $2
  AND deleted_at IS NULL
FOR UPDATE
`

type LockSessionRuntimeFenceForActivationParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	BotID     pgtype.UUID `json:"bot_id"`
}

func (q *Queries) LockSessionRuntimeFenceForActivation(ctx context.Context, arg LockSessionRuntimeFenceForActivationParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockSessionRuntimeFenceForActivation, arg.SessionID, arg.BotID)
	var runtime_fencing_token int64
	err := row.Scan(&runtime_fencing_token)
	return runtime_fencing_token, err
}

const nextSessionRuntimeFenceToken = `-- name: NextSessionRuntimeFenceToken :one
SELECT nextval('session_runtime_fencing_token_seq')::bigint
`

func (q *Queries) NextSessionRuntimeFenceToken(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextSessionRuntimeFenceToken)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setSessionNextTurnPosition = `-- name: SetSessionNextTurnPosition :exec
UPDATE bot_sessions
SET next_turn_position = $1::bigint
WHERE team_id = public.sophia_current_team_id() AND id = $2
`

type SetSessionNextTurnPositionParams struct {
	NextTurnPosition int64       `json:"next_turn_position"`
	SessionID        pgtype.UUID `json:"session_id"`
}

func (q *Queries) SetSessionNextTurnPosition(ctx context.Context, arg SetSessionNextTurnPositionParams) error {
	_, err := q.db.Exec(ctx, setSessionNextTurnPosition, arg.NextTurnPosition, arg.SessionID)
	return err
}

const softDeleteSession = `-- name: SoftDeleteSession :exec
UPDATE bot_sessions
SET deleted_at = now(), updated_at = now()
WHERE team_id = public.sophia_current_team_id() AND id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSession, id)
	return err
}

const softDeleteSessionsByBot = `-- name: SoftDeleteSessionsByBot :exec
UPDATE bot_sessions
SET deleted_at = now(), updated_at = now()
WHERE team_id = public.sophia_current_team_id() AND bot_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSessionsByBot(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSessionsByBot, botID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE bot_sessions
SET updated_at = now()
WHERE team_id = public.sophia_current_team_id() AND id = $1 AND deleted_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateSessionMetadata = `-- name: UpdateSessionMetadata :one
UPDATE bot_sessions
SET metadata = $1, updated_at = now()
WHERE team_id = public.sophia_current_team_id() AND id = $2 AND deleted_at IS NULL
RETURNING id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, compaction_epoch, runtime_fencing_token, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at, team_id
`

type UpdateSessionMetadataParams struct {
	Metadata []byte      `json:"metadata"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSessionMetadata(ctx context.Context, arg UpdateSessionMetadataParams) (BotSession, error) {
	row := q.db.QueryRow(ctx, updateSessionMetadata, arg.Metadata, arg.ID)
	var i BotSession
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RouteID,
		&i.ChannelType,
		&i.Type,
		&i.SessionMode,
		&i.RuntimeType,
		&i.RuntimeMetadata,
		&i.Title,
		&i.Metadata,
		&i.NextTurnPosition,
		&i.CompactionEpoch,
		&i.RuntimeFencingToken,
		&i.ParentSessionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
	)
	return i, err
}

const updateSessionMetadataWithRuntimeFence = `-- name: UpdateSessionMetadataWithRuntimeFence :one
UPDATE bot_sessions
SET metadata = $1, updated_at = now()
WHERE team_id = public.sophia_current_team_id()
  AND id = $2
  AND bot_id = $3
  AND runtime_fencing_token = $4
  AND deleted_at IS NULL
RETURNING id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, compaction_epoch, runtime_fencing_token, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at, team_id
`

type UpdateSessionMetadataWithRuntimeFenceParams struct {
	Metadata            []byte      `json:"metadata"`
	ID                  pgtype.UUID `json:"id"`
	BotID               pgtype.UUID `json:"bot_id"`
	RuntimeFencingToken int64       `json:"runtime_fencing_token"`
}

func (q *Queries) UpdateSessionMetadataWithRuntimeFence(ctx context.Context, arg UpdateSessionMetadataWithRuntimeFenceParams) (BotSession, error) {
	row := q.db.QueryRow(ctx, updateSessionMetadataWithRuntimeFence,
		arg.Metadata,
		arg.ID,
		arg.BotID,
		arg.RuntimeFencingToken,
	)
	var i BotSession
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RouteID,
		&i.ChannelType,
		&i.Type,
		&i.SessionMode,
		&i.RuntimeType,
		&i.RuntimeMetadata,
		&i.Title,
		&i.Metadata,
		&i.NextTurnPosition,
		&i.CompactionEpoch,
		&i.RuntimeFencingToken,
		&i.ParentSessionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
	)
	return i, err
}

const updateSessionTitle = `-- name: UpdateSessionTitle :one
UPDATE bot_sessions
SET title = $1, updated_at = now()
WHERE team_id = public.sophia_current_team_id() AND id = $2 AND deleted_at IS NULL
RETURNING id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, compaction_epoch, runtime_fencing_token, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at, team_id
`

type UpdateSessionTitleParams struct {
	Title string      `json:"title"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) (BotSession, error) {
	row := q.db.QueryRow(ctx, updateSessionTitle, arg.Title, arg.ID)
	var i BotSession
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RouteID,
		&i.ChannelType,
		&i.Type,
		&i.SessionMode,
		&i.RuntimeType,
		&i.RuntimeMetadata,
		&i.Title,
		&i.Metadata,
		&i.NextTurnPosition,
		&i.CompactionEpoch,
		&i.RuntimeFencingToken,
		&i.ParentSessionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
	)
	return i, err
}

const updateSessionTitleWithRuntimeFence = `-- name: UpdateSessionTitleWithRuntimeFence :one
UPDATE bot_sessions
SET title = $1, updated_at = now()
WHERE team_id = public.sophia_current_team_id()
  AND id = $2
  AND bot_id = $3
  AND runtime_fencing_token = $4
  AND deleted_at IS NULL
RETURNING id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, compaction_epoch, runtime_fencing_token, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at, team_id
`

type UpdateSessionTitleWithRuntimeFenceParams struct {
	Title               string      `json:"title"`
	ID                  pgtype.UUID `json:"id"`
	BotID               pgtype.UUID `json:"bot_id"`
	RuntimeFencingToken int64       `json:"runtime_fencing_token"`
}

func (q *Queries) UpdateSessionTitleWithRuntimeFence(ctx context.Context, arg UpdateSessionTitleWithRuntimeFenceParams) (BotSession, error) {
	row := q.db.QueryRow(ctx, updateSessionTitleWithRuntimeFence,
		arg.Title,
		arg.ID,
		arg.BotID,
		arg.RuntimeFencingToken,
	)
	var i BotSession
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RouteID,
		&i.ChannelType,
		&i.Type,
		&i.SessionMode,
		&i.RuntimeType,
		&i.RuntimeMetadata,
		&i.Title,
		&i.Metadata,
		&i.NextTurnPosition,
		&i.CompactionEpoch,
		&i.RuntimeFencingToken,
		&i.ParentSessionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
	)
	return i, err
}

const updateSessionTypeAndMetadata = `-- name: UpdateSessionTypeAndMetadata :one
UPDATE bot_sessions
SET type = $1,
    session_mode = $2,
    runtime_type = $3,
    runtime_metadata = $4,
    metadata = $5,
    updated_at = now()
WHERE team_id = public.sophia_current_team_id() AND id = $6 AND deleted_at IS NULL
RETURNING id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, compaction_epoch, runtime_fencing_token, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at, team_id
`

type UpdateSessionTypeAndMetadataParams struct {
	Type            string      `json:"type"`
	SessionMode     string      `json:"session_mode"`
	RuntimeType     string      `json:"runtime_type"`
	RuntimeMetadata []byte      `json:"runtime_metadata"`
	Metadata        []byte      `json:"metadata"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSessionTypeAndMetadata(ctx context.Context, arg UpdateSessionTypeAndMetadataParams) (BotSession, error) {
	row := q.db.QueryRow(ctx, updateSessionTypeAndMetadata,
		arg.Type,
		arg.SessionMode,
		arg.RuntimeType,
		arg.RuntimeMetadata,
		arg.Metadata,
		arg.ID,
	)
	var i BotSession
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RouteID,
		&i.ChannelType,
		&i.Type,
		&i.SessionMode,
		&i.RuntimeType,
		&i.RuntimeMetadata,
		&i.Title,
		&i.Metadata,
		&i.NextTurnPosition,
		&i.CompactionEpoch,
		&i.RuntimeFencingToken,
		&i.ParentSessionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
	)
	return i, err
}

const upsertSessionDiscussCursor = `-- name: UpsertSessionDiscussCursor :one
INSERT INTO bot_session_discuss_cursors (
  session_id, scope_key, route_id, source, consumed_cursor, consumed_event_cursor
)
VALUES (
  $1,
  $2,
  $3::uuid,
  $4,
  $5,
  $6
)
ON CONFLICT (team_id, session_id, scope_key) DO UPDATE
SET route_id = COALESCE(EXCLUDED.route_id, bot_session_discuss_cursors.route_id),
    source = EXCLUDED.source,
    consumed_cursor = GREATEST(bot_session_discuss_cursors.consumed_cursor, EXCLUDED.consumed_cursor),
    consumed_event_cursor = GREATEST(bot_session_discuss_cursors.consumed_event_cursor, EXCLUDED.consumed_event_cursor),
    updated_at = now()
RETURNING session_id, scope_key, route_id, source, consumed_cursor, consumed_event_cursor, updated_at, team_id
`

type UpsertSessionDiscussCursorParams struct {
	SessionID           pgtype.UUID `json:"session_id"`
	ScopeKey            string      `json:"scope_key"`
	RouteID             pgtype.UUID `json:"route_id"`
	Source              string      `json:"source"`
	ConsumedCursor      int64       `json:"consumed_cursor"`
	ConsumedEventCursor int64       `json:"consumed_event_cursor"`
}

func (q *Queries) UpsertSessionDiscussCursor(ctx context.Context, arg UpsertSessionDiscussCursorParams) (BotSessionDiscussCursor, error) {
	row := q.db.QueryRow(ctx, upsertSessionDiscussCursor,
		arg.SessionID,
		arg.ScopeKey,
		arg.RouteID,
		arg.Source,
		arg.ConsumedCursor,
		arg.ConsumedEventCursor,
	)
	var i BotSessionDiscussCursor
	err := row.Scan(
		&i.SessionID,
		&i.ScopeKey,
		&i.RouteID,
		&i.Source,
		&i.ConsumedCursor,
		&i.ConsumedEventCursor,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}
