// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const admitSessionRun = `-- name: AdmitSessionRun :one
WITH target_session AS (
  SELECT s.id AS session_id
  FROM bot_sessions AS s
  WHERE s.team_id = public.sophia_current_team_id()
    AND s.id = $7
    AND s.deleted_at IS NULL
),
existing AS (
  SELECT 1 AS present
  FROM session_runs AS prior
  WHERE prior.team_id = public.sophia_current_team_id()
    AND prior.session_id = $7
    AND prior.invocation_id = $3
),
allocated_position AS (
  UPDATE bot_sessions AS s
  SET next_turn_position = s.next_turn_position + 1
  FROM target_session
  WHERE s.team_id = public.sophia_current_team_id()
    AND s.id = target_session.session_id
    AND NOT EXISTS (SELECT 1 FROM existing)
  RETURNING (s.next_turn_position - 1)::bigint AS turn_position
)
INSERT INTO session_runs (
  run_id,
  bot_id,
  session_id,
  invocation_id,
  turn_id,
  turn_position,
  state,
  input_json,
  input_fingerprint
)
SELECT
  $1,
  $2,
  target_session.session_id,
  $3,
  $4,
  allocated_position.turn_position,
  'accepted',
  $5,
  $6
FROM target_session
CROSS JOIN allocated_position
ON CONFLICT (team_id, session_id, invocation_id) DO NOTHING
RETURNING run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, error_code, error_message, created_at, updated_at
`

type AdmitSessionRunParams struct {
	RunID            pgtype.UUID `json:"run_id"`
	BotID            pgtype.UUID `json:"bot_id"`
	InvocationID     string      `json:"invocation_id"`
	TurnID           pgtype.UUID `json:"turn_id"`
	InputJson        []byte      `json:"input_json"`
	InputFingerprint string      `json:"input_fingerprint"`
	SessionID        pgtype.UUID `json:"session_id"`
}

// Durable admission. There is no queue: SR-OWN-001 permits answering busy, so a
// second concurrent invocation is rejected rather than parked.
//
// Busy is rejected in two layers. The adapter's indexed pre-read catches the
// common case before this statement runs at all, so contended submissions never
// reach the write path. This statement handles only what slipped through that
// unlocked read: session_runs_single_active raises, and because the statement is
// one implicit transaction the rollback takes the allocated turn position with
// it, leaving nothing behind for the caller to clean up.
//
// Returns no rows when this invocation_id was already admitted — ON CONFLICT
// keeps the ordinary retry path free of errors, which matters because channel
// redelivery makes it a routine event — or when the session does not exist. The
// caller re-selects by invocation to tell those two apart.
//
// A position is allocated only for an admission that can still succeed: never
// for a known duplicate (the NOT EXISTS guard below) and never for a rejected
// one (the rollback). The single exception is two callers racing on the *same*
// invocation_id, where both pass the guard against the statement snapshot and
// the loser's increment commits with no row. That leaves a gap in turn_position,
// which is ordering-only and never read as a count.
func (q *Queries) AdmitSessionRun(ctx context.Context, arg AdmitSessionRunParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, admitSessionRun,
		arg.RunID,
		arg.BotID,
		arg.InvocationID,
		arg.TurnID,
		arg.InputJson,
		arg.InputFingerprint,
		arg.SessionID,
	)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimSessionRun = `-- name: ClaimSessionRun :one
UPDATE session_runs
SET owner_id = $1,
    owner_since = now(),
    fencing_token = $2,
    live_generation = $3,
    state = 'running',
    updated_at = now()
WHERE team_id = public.sophia_current_team_id()
  AND run_id = $4
  AND state = 'accepted'
  AND fencing_token < $2
RETURNING run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, error_code, error_message, created_at, updated_at
`

type ClaimSessionRunParams struct {
	OwnerID        pgtype.Text `json:"owner_id"`
	FencingToken   int64       `json:"fencing_token"`
	LiveGeneration pgtype.Text `json:"live_generation"`
	RunID          pgtype.UUID `json:"run_id"`
}

// Ownership change: the only write that touches owner_id, fencing_token,
// owner_since and live_generation. live_generation is stamped once here and
// never updated, which keeps idx_session_runs_recovery a stable keyset cursor.
// Fencing tokens come from a monotonic sequence, so a newer claim always
// carries a strictly larger token than the one it replaces.
func (q *Queries) ClaimSessionRun(ctx context.Context, arg ClaimSessionRunParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, claimSessionRun,
		arg.OwnerID,
		arg.FencingToken,
		arg.LiveGeneration,
		arg.RunID,
	)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finalizeSessionRun = `-- name: FinalizeSessionRun :one
UPDATE session_runs
SET state = CASE
        WHEN $1::text = 'lost' AND abort_requested_at IS NOT NULL THEN 'aborted'
        ELSE $1::text
    END,
    error_code = CASE
        WHEN $1::text = 'lost' AND abort_requested_at IS NOT NULL THEN NULL
        ELSE $2::text
    END,
    error_message = CASE
        WHEN $1::text = 'lost' AND abort_requested_at IS NOT NULL THEN NULL
        ELSE $3::text
    END,
    updated_at = now()
WHERE team_id = public.sophia_current_team_id()
  AND run_id = $4
  AND fencing_token = $5
  AND state IN ('accepted', 'running', 'waiting_decision')
RETURNING run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, error_code, error_message, created_at, updated_at
`

type FinalizeSessionRunParams struct {
	State        string      `json:"state"`
	ErrorCode    pgtype.Text `json:"error_code"`
	ErrorMessage pgtype.Text `json:"error_message"`
	RunID        pgtype.UUID `json:"run_id"`
	FencingToken int64       `json:"fencing_token"`
}

// Fenced idempotent terminal write, shared by the owner (completed / aborted /
// failed) and the reaper (lost). Zero rows affected means the transition was
// already applied or a newer owner superseded this token; neither is an error.
func (q *Queries) FinalizeSessionRun(ctx context.Context, arg FinalizeSessionRunParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, finalizeSessionRun,
		arg.State,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.RunID,
		arg.FencingToken,
	)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSessionRun = `-- name: GetActiveSessionRun :one
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, error_code, error_message, created_at, updated_at
FROM session_runs
WHERE team_id = public.sophia_current_team_id()
  AND session_id = $1
  AND state IN ('accepted', 'running', 'waiting_decision')
`

func (q *Queries) GetActiveSessionRun(ctx context.Context, sessionID pgtype.UUID) (SessionRun, error) {
	row := q.db.QueryRow(ctx, getActiveSessionRun, sessionID)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestSessionRun = `-- name: GetLatestSessionRun :one
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, error_code, error_message, created_at, updated_at
FROM session_runs
WHERE team_id = public.sophia_current_team_id()
  AND session_id = $1
ORDER BY created_at DESC, run_id DESC
LIMIT 1
`

func (q *Queries) GetLatestSessionRun(ctx context.Context, sessionID pgtype.UUID) (SessionRun, error) {
	row := q.db.QueryRow(ctx, getLatestSessionRun, sessionID)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionRun = `-- name: GetSessionRun :one
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, error_code, error_message, created_at, updated_at
FROM session_runs
WHERE team_id = public.sophia_current_team_id()
  AND run_id = $1
`

func (q *Queries) GetSessionRun(ctx context.Context, runID pgtype.UUID) (SessionRun, error) {
	row := q.db.QueryRow(ctx, getSessionRun, runID)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionRunByInvocation = `-- name: GetSessionRunByInvocation :one
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, error_code, error_message, created_at, updated_at
FROM session_runs
WHERE team_id = public.sophia_current_team_id()
  AND session_id = $1
  AND invocation_id = $2
`

type GetSessionRunByInvocationParams struct {
	SessionID    pgtype.UUID `json:"session_id"`
	InvocationID string      `json:"invocation_id"`
}

func (q *Queries) GetSessionRunByInvocation(ctx context.Context, arg GetSessionRunByInvocationParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, getSessionRunByInvocation, arg.SessionID, arg.InvocationID)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrphanedSessionRuns = `-- name: ListOrphanedSessionRuns :many
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, error_code, error_message, created_at, updated_at
FROM session_runs
WHERE team_id = public.sophia_current_team_id()
  AND state = 'accepted'
  AND owner_id IS NULL
  AND created_at < now() - make_interval(secs => $1::double precision)
ORDER BY created_at, run_id
LIMIT $2
`

type ListOrphanedSessionRunsParams struct {
	GraceSeconds float64 `json:"grace_seconds"`
	BatchSize    int32   `json:"batch_size"`
}

// Admission committed but the process died before reserving the run in the live
// backend. No lease exists, so these never appear as expiry candidates and no
// generation change implicates them. A single leader reaper reads this, so no
// row locking is needed.
func (q *Queries) ListOrphanedSessionRuns(ctx context.Context, arg ListOrphanedSessionRunsParams) ([]SessionRun, error) {
	rows, err := q.db.Query(ctx, listOrphanedSessionRuns, arg.GraceSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionRun
	for rows.Next() {
		var i SessionRun
		if err := rows.Scan(
			&i.RunID,
			&i.TeamID,
			&i.BotID,
			&i.SessionID,
			&i.InvocationID,
			&i.TurnID,
			&i.TurnPosition,
			&i.State,
			&i.InputJson,
			&i.InputFingerprint,
			&i.OwnerID,
			&i.FencingToken,
			&i.OwnerSince,
			&i.LiveGeneration,
			&i.AbortRequestedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleGenerationSessionRuns = `-- name: ListStaleGenerationSessionRuns :many
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, error_code, error_message, created_at, updated_at
FROM session_runs
WHERE team_id = public.sophia_current_team_id()
  AND state IN ('accepted', 'running', 'waiting_decision')
  AND live_generation IS NOT NULL
  AND live_generation <> $1
  AND (
    $2::text IS NULL
    OR live_generation > $2
    OR (live_generation = $2 AND run_id > $3)
  )
ORDER BY live_generation, run_id
LIMIT $4
`

type ListStaleGenerationSessionRunsParams struct {
	CurrentGeneration pgtype.Text `json:"current_generation"`
	CursorGeneration  pgtype.Text `json:"cursor_generation"`
	CursorRunID       pgtype.UUID `json:"cursor_run_id"`
	BatchSize         int32       `json:"batch_size"`
}

// Fail-closed recovery sweep. Matching on "not the current generation" rather
// than one specific old value means a backend lost twice in quick succession
// cannot strand rows from the older incarnation. Orphans are excluded by
// live_generation IS NOT NULL: they were never claimed.
//
// A NULL cursor means "start from the beginning" and must be spelled out: the
// keyset comparison below is NULL for every row when the cursor is NULL, so
// without this branch the first batch of every sweep matches nothing, and a
// sweep that never returns a full batch never advances past it either.
func (q *Queries) ListStaleGenerationSessionRuns(ctx context.Context, arg ListStaleGenerationSessionRunsParams) ([]SessionRun, error) {
	rows, err := q.db.Query(ctx, listStaleGenerationSessionRuns,
		arg.CurrentGeneration,
		arg.CursorGeneration,
		arg.CursorRunID,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionRun
	for rows.Next() {
		var i SessionRun
		if err := rows.Scan(
			&i.RunID,
			&i.TeamID,
			&i.BotID,
			&i.SessionID,
			&i.InvocationID,
			&i.TurnID,
			&i.TurnPosition,
			&i.State,
			&i.InputJson,
			&i.InputFingerprint,
			&i.OwnerID,
			&i.FencingToken,
			&i.OwnerSince,
			&i.LiveGeneration,
			&i.AbortRequestedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSessionRunFencingToken = `-- name: NextSessionRunFencingToken :one
SELECT nextval('session_runtime_fencing_token_seq')::bigint AS token
`

func (q *Queries) NextSessionRunFencingToken(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextSessionRunFencingToken)
	var token int64
	err := row.Scan(&token)
	return token, err
}

const reclaimWaitingDecisionSessionRun = `-- name: ReclaimWaitingDecisionSessionRun :one
UPDATE session_runs
SET owner_id = $1,
    owner_since = now(),
    fencing_token = $2,
    live_generation = $3,
    updated_at = now()
WHERE team_id = public.sophia_current_team_id()
  AND run_id = $4
  AND state = 'waiting_decision'
  AND fencing_token = $5
  AND fencing_token < $2
RETURNING run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, error_code, error_message, created_at, updated_at
`

type ReclaimWaitingDecisionSessionRunParams struct {
	OwnerID              pgtype.Text `json:"owner_id"`
	NewFencingToken      int64       `json:"new_fencing_token"`
	LiveGeneration       pgtype.Text `json:"live_generation"`
	RunID                pgtype.UUID `json:"run_id"`
	PreviousFencingToken int64       `json:"previous_fencing_token"`
}

// Recovery advances both durable ownership and the backend incarnation while
// preserving waiting_decision. The previous token is the CAS guard; the new
// token must be strictly newer so a stale reaper can never move ownership
// backwards.
func (q *Queries) ReclaimWaitingDecisionSessionRun(ctx context.Context, arg ReclaimWaitingDecisionSessionRunParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, reclaimWaitingDecisionSessionRun,
		arg.OwnerID,
		arg.NewFencingToken,
		arg.LiveGeneration,
		arg.RunID,
		arg.PreviousFencingToken,
	)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requestSessionRunAbort = `-- name: RequestSessionRunAbort :one
UPDATE session_runs
SET abort_requested_at = COALESCE(abort_requested_at, now()),
    updated_at = now()
WHERE team_id = public.sophia_current_team_id()
  AND run_id = $1
  AND state IN ('accepted', 'running', 'waiting_decision')
RETURNING run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, error_code, error_message, created_at, updated_at
`

// Not fenced: abort is a user intent that may arrive at any instance, and the
// owner applies it. Repeating it keeps the first request time.
func (q *Queries) RequestSessionRunAbort(ctx context.Context, runID pgtype.UUID) (SessionRun, error) {
	row := q.db.QueryRow(ctx, requestSessionRunAbort, runID)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resumeSessionRun = `-- name: ResumeSessionRun :one
UPDATE session_runs
SET state = 'running',
    updated_at = now()
WHERE team_id = public.sophia_current_team_id()
  AND run_id = $1
  AND fencing_token = $2
  AND state IN ('running', 'waiting_decision')
RETURNING run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, error_code, error_message, created_at, updated_at
`

type ResumeSessionRunParams struct {
	RunID        pgtype.UUID `json:"run_id"`
	FencingToken int64       `json:"fencing_token"`
}

func (q *Queries) ResumeSessionRun(ctx context.Context, arg ResumeSessionRunParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, resumeSessionRun, arg.RunID, arg.FencingToken)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSessionRunWaitingDecision = `-- name: SetSessionRunWaitingDecision :one
UPDATE session_runs
SET state = 'waiting_decision',
    updated_at = now()
WHERE team_id = public.sophia_current_team_id()
  AND run_id = $1
  AND fencing_token = $2
  AND state IN ('running', 'waiting_decision')
RETURNING run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, error_code, error_message, created_at, updated_at
`

type SetSessionRunWaitingDecisionParams struct {
	RunID        pgtype.UUID `json:"run_id"`
	FencingToken int64       `json:"fencing_token"`
}

func (q *Queries) SetSessionRunWaitingDecision(ctx context.Context, arg SetSessionRunWaitingDecisionParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, setSessionRunWaitingDecision, arg.RunID, arg.FencingToken)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
