// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSettingsByBotID = `-- name: DeleteSettingsByBotID :exec
UPDATE bots
SET language = 'auto',
    command_ui_language = 'auto',
    reasoning_enabled = false,
    reasoning_effort = 'medium',
    heartbeat_enabled = false,
    heartbeat_interval = 1440,
    heartbeat_prompt = '',
    compaction_enabled = true,
    compaction_threshold = 0,
    compaction_target_percent = NULL,
    chat_model_id = NULL,
    chat_runtime = 'model',
    chat_acp_agent_id = NULL,
    chat_acp_project_path = '/data',
    chat_acp_project_mode = 'project',
    heartbeat_model_id = NULL,
    compaction_model_id = NULL,
    image_model_id = NULL,
    search_provider_id = NULL,
    fetch_provider_id = NULL,
    memory_provider_id = NULL,
    tts_model_id = NULL,
    transcription_model_id = NULL,
    video_model_id = NULL,
    persist_full_tool_results = false,
    show_tool_calls_in_im = false,
    tool_approval_config = '{"enabled":false,"read":{"require_approval":false,"bypass_globs":[],"force_review_globs":[]},"write":{"require_approval":true,"bypass_globs":["/data/**","/tmp/**"],"force_review_globs":[]},"exec":{"require_approval":false,"bypass_commands":[],"force_review_commands":[]}}'::jsonb,
    display_enabled = false,
    overlay_provider = '',
    overlay_enabled = false,
    overlay_config = '{}'::jsonb,
    updated_at = now()
WHERE team_id = public.sophia_current_team_id() AND id = $1
`

func (q *Queries) DeleteSettingsByBotID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSettingsByBotID, id)
	return err
}

const getSettingsByBotID = `-- name: GetSettingsByBotID :one
SELECT
  bots.id AS bot_id,
  bots.language,
  bots.reasoning_enabled,
  bots.reasoning_effort,
  bots.heartbeat_enabled,
  bots.heartbeat_interval,
  bots.heartbeat_prompt,
  bots.compaction_enabled,
  bots.compaction_threshold,
  bots.compaction_target_percent,
  bots.timezone,
  chat_models.id AS chat_model_id,
  bots.chat_runtime,
  bots.chat_acp_agent_id,
  bots.chat_acp_project_path,
  bots.chat_acp_project_mode,
  heartbeat_models.id AS heartbeat_model_id,
  compaction_models.id AS compaction_model_id,
  search_providers.id AS search_provider_id,
  fetch_providers.id AS fetch_provider_id,
  memory_providers.id AS memory_provider_id,
  image_models.id AS image_model_id,
  tts_models.id AS tts_model_id,
  transcription_models.id AS transcription_model_id,
  video_models.id AS video_model_id,
  bots.persist_full_tool_results,
  bots.show_tool_calls_in_im,
  bots.tool_approval_config,
  bots.display_enabled,
  bots.overlay_provider,
  bots.overlay_enabled,
  bots.overlay_config,
  bots.command_ui_language
FROM bots
LEFT JOIN models AS chat_models ON chat_models.id = bots.chat_model_id AND chat_models.team_id = public.sophia_current_team_id()
LEFT JOIN models AS heartbeat_models ON heartbeat_models.id = bots.heartbeat_model_id AND heartbeat_models.team_id = public.sophia_current_team_id()
LEFT JOIN models AS compaction_models ON compaction_models.id = bots.compaction_model_id AND compaction_models.team_id = public.sophia_current_team_id()
LEFT JOIN models AS image_models ON image_models.id = bots.image_model_id AND image_models.team_id = public.sophia_current_team_id()
LEFT JOIN search_providers ON search_providers.id = bots.search_provider_id AND search_providers.team_id = public.sophia_current_team_id()
LEFT JOIN fetch_providers ON fetch_providers.id = bots.fetch_provider_id AND fetch_providers.team_id = public.sophia_current_team_id()
LEFT JOIN memory_providers ON memory_providers.id = bots.memory_provider_id AND memory_providers.team_id = public.sophia_current_team_id()
LEFT JOIN models AS tts_models ON tts_models.id = bots.tts_model_id AND tts_models.team_id = public.sophia_current_team_id()
LEFT JOIN models AS transcription_models ON transcription_models.id = bots.transcription_model_id AND transcription_models.team_id = public.sophia_current_team_id()
LEFT JOIN models AS video_models ON video_models.id = bots.video_model_id AND video_models.team_id = public.sophia_current_team_id()
WHERE bots.team_id = public.sophia_current_team_id() AND bots.id = $1
`

type GetSettingsByBotIDRow struct {
	BotID                   pgtype.UUID `json:"bot_id"`
	Language                string      `json:"language"`
	ReasoningEnabled        bool        `json:"reasoning_enabled"`
	ReasoningEffort         string      `json:"reasoning_effort"`
	HeartbeatEnabled        bool        `json:"heartbeat_enabled"`
	HeartbeatInterval       int32       `json:"heartbeat_interval"`
	HeartbeatPrompt         string      `json:"heartbeat_prompt"`
	CompactionEnabled       bool        `json:"compaction_enabled"`
	CompactionThreshold     int32       `json:"compaction_threshold"`
	CompactionTargetPercent pgtype.Int4 `json:"compaction_target_percent"`
	Timezone                pgtype.Text `json:"timezone"`
	ChatModelID             pgtype.UUID `json:"chat_model_id"`
	ChatRuntime             string      `json:"chat_runtime"`
	ChatAcpAgentID          pgtype.Text `json:"chat_acp_agent_id"`
	ChatAcpProjectPath      string      `json:"chat_acp_project_path"`
	ChatAcpProjectMode      string      `json:"chat_acp_project_mode"`
	HeartbeatModelID        pgtype.UUID `json:"heartbeat_model_id"`
	CompactionModelID       pgtype.UUID `json:"compaction_model_id"`
	SearchProviderID        pgtype.UUID `json:"search_provider_id"`
	FetchProviderID         pgtype.UUID `json:"fetch_provider_id"`
	MemoryProviderID        pgtype.UUID `json:"memory_provider_id"`
	ImageModelID            pgtype.UUID `json:"image_model_id"`
	TtsModelID              pgtype.UUID `json:"tts_model_id"`
	TranscriptionModelID    pgtype.UUID `json:"transcription_model_id"`
	VideoModelID            pgtype.UUID `json:"video_model_id"`
	PersistFullToolResults  bool        `json:"persist_full_tool_results"`
	ShowToolCallsInIm       bool        `json:"show_tool_calls_in_im"`
	ToolApprovalConfig      []byte      `json:"tool_approval_config"`
	DisplayEnabled          bool        `json:"display_enabled"`
	OverlayProvider         string      `json:"overlay_provider"`
	OverlayEnabled          bool        `json:"overlay_enabled"`
	OverlayConfig           []byte      `json:"overlay_config"`
	CommandUiLanguage       string      `json:"command_ui_language"`
}

func (q *Queries) GetSettingsByBotID(ctx context.Context, id pgtype.UUID) (GetSettingsByBotIDRow, error) {
	row := q.db.QueryRow(ctx, getSettingsByBotID, id)
	var i GetSettingsByBotIDRow
	err := row.Scan(
		&i.BotID,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionTargetPercent,
		&i.Timezone,
		&i.ChatModelID,
		&i.ChatRuntime,
		&i.ChatAcpAgentID,
		&i.ChatAcpProjectPath,
		&i.ChatAcpProjectMode,
		&i.HeartbeatModelID,
		&i.CompactionModelID,
		&i.SearchProviderID,
		&i.FetchProviderID,
		&i.MemoryProviderID,
		&i.ImageModelID,
		&i.TtsModelID,
		&i.TranscriptionModelID,
		&i.VideoModelID,
		&i.PersistFullToolResults,
		&i.ShowToolCallsInIm,
		&i.ToolApprovalConfig,
		&i.DisplayEnabled,
		&i.OverlayProvider,
		&i.OverlayEnabled,
		&i.OverlayConfig,
		&i.CommandUiLanguage,
	)
	return i, err
}

const upsertBotSettings = `-- name: UpsertBotSettings :one
WITH updated AS (
  UPDATE bots
  SET language = $1,
      reasoning_enabled = $2,
      reasoning_effort = $3,
      heartbeat_enabled = $4,
      heartbeat_interval = $5,
      heartbeat_prompt = $6,
      compaction_enabled = $7,
      compaction_threshold = $8,
      compaction_target_percent = CASE
        WHEN $9::boolean
          THEN $10::integer
        ELSE bots.compaction_target_percent
      END,
      timezone = COALESCE($11::text, bots.timezone),
      chat_model_id = COALESCE($12::uuid, bots.chat_model_id),
      chat_runtime = $13,
      chat_acp_agent_id = $14::text,
      chat_acp_project_path = $15,
      chat_acp_project_mode = $16,
      heartbeat_model_id = COALESCE($17::uuid, bots.heartbeat_model_id),
      compaction_model_id = CASE
        WHEN $18::boolean THEN $19::uuid
        ELSE bots.compaction_model_id
      END,
      search_provider_id = COALESCE($20::uuid, bots.search_provider_id),
      fetch_provider_id = CASE
        WHEN $21::boolean THEN $22::uuid
        ELSE bots.fetch_provider_id
      END,
      memory_provider_id = COALESCE($23::uuid, bots.memory_provider_id),
      image_model_id = COALESCE($24::uuid, bots.image_model_id),
      tts_model_id = COALESCE($25::uuid, bots.tts_model_id),
      transcription_model_id = COALESCE($26::uuid, bots.transcription_model_id),
      video_model_id = COALESCE($27::uuid, bots.video_model_id),
      persist_full_tool_results = $28,
      show_tool_calls_in_im = $29,
      tool_approval_config = $30,
      display_enabled = $31,
      overlay_provider = $32,
      overlay_enabled = $33,
      overlay_config = $34,
      command_ui_language = $35,
      updated_at = now()
  WHERE bots.team_id = public.sophia_current_team_id() AND bots.id = $36
  RETURNING bots.id, bots.language, bots.reasoning_enabled, bots.reasoning_effort, bots.heartbeat_enabled, bots.heartbeat_interval, bots.heartbeat_prompt, bots.compaction_enabled, bots.compaction_threshold, bots.compaction_target_percent, bots.timezone, bots.chat_model_id, bots.chat_runtime, bots.chat_acp_agent_id, bots.chat_acp_project_path, bots.chat_acp_project_mode, bots.heartbeat_model_id, bots.compaction_model_id, bots.image_model_id, bots.search_provider_id, bots.fetch_provider_id, bots.memory_provider_id, bots.tts_model_id, bots.transcription_model_id, bots.video_model_id, bots.persist_full_tool_results, bots.show_tool_calls_in_im, bots.tool_approval_config, bots.display_enabled, bots.overlay_provider, bots.overlay_enabled, bots.overlay_config, bots.command_ui_language
)
SELECT
  updated.id AS bot_id,
  updated.language,
  updated.reasoning_enabled,
  updated.reasoning_effort,
  updated.heartbeat_enabled,
  updated.heartbeat_interval,
  updated.heartbeat_prompt,
  updated.compaction_enabled,
  updated.compaction_threshold,
  updated.compaction_target_percent,
  updated.timezone,
  chat_models.id AS chat_model_id,
  updated.chat_runtime,
  updated.chat_acp_agent_id,
  updated.chat_acp_project_path,
  updated.chat_acp_project_mode,
  heartbeat_models.id AS heartbeat_model_id,
  compaction_models.id AS compaction_model_id,
  search_providers.id AS search_provider_id,
  fetch_providers.id AS fetch_provider_id,
  memory_providers.id AS memory_provider_id,
  image_models.id AS image_model_id,
  tts_models.id AS tts_model_id,
  transcription_models.id AS transcription_model_id,
  video_models.id AS video_model_id,
  updated.persist_full_tool_results,
  updated.show_tool_calls_in_im,
  updated.tool_approval_config,
  updated.display_enabled,
  updated.overlay_provider,
  updated.overlay_enabled,
  updated.overlay_config,
  updated.command_ui_language
FROM updated
LEFT JOIN models AS chat_models ON chat_models.id = updated.chat_model_id AND chat_models.team_id = public.sophia_current_team_id()
LEFT JOIN models AS heartbeat_models ON heartbeat_models.id = updated.heartbeat_model_id AND heartbeat_models.team_id = public.sophia_current_team_id()
LEFT JOIN models AS compaction_models ON compaction_models.id = updated.compaction_model_id AND compaction_models.team_id = public.sophia_current_team_id()
LEFT JOIN models AS image_models ON image_models.id = updated.image_model_id AND image_models.team_id = public.sophia_current_team_id()
LEFT JOIN search_providers ON search_providers.id = updated.search_provider_id AND search_providers.team_id = public.sophia_current_team_id()
LEFT JOIN fetch_providers ON fetch_providers.id = updated.fetch_provider_id AND fetch_providers.team_id = public.sophia_current_team_id()
LEFT JOIN memory_providers ON memory_providers.id = updated.memory_provider_id AND memory_providers.team_id = public.sophia_current_team_id()
LEFT JOIN models AS tts_models ON tts_models.id = updated.tts_model_id AND tts_models.team_id = public.sophia_current_team_id()
LEFT JOIN models AS transcription_models ON transcription_models.id = updated.transcription_model_id AND transcription_models.team_id = public.sophia_current_team_id()
LEFT JOIN models AS video_models ON video_models.id = updated.video_model_id AND video_models.team_id = public.sophia_current_team_id()
`

type UpsertBotSettingsParams struct {
	Language                   string      `json:"language"`
	ReasoningEnabled           bool        `json:"reasoning_enabled"`
	ReasoningEffort            string      `json:"reasoning_effort"`
	HeartbeatEnabled           bool        `json:"heartbeat_enabled"`
	HeartbeatInterval          int32       `json:"heartbeat_interval"`
	HeartbeatPrompt            string      `json:"heartbeat_prompt"`
	CompactionEnabled          bool        `json:"compaction_enabled"`
	CompactionThreshold        int32       `json:"compaction_threshold"`
	CompactionTargetPercentSet bool        `json:"compaction_target_percent_set"`
	CompactionTargetPercent    pgtype.Int4 `json:"compaction_target_percent"`
	Timezone                   pgtype.Text `json:"timezone"`
	ChatModelID                pgtype.UUID `json:"chat_model_id"`
	ChatRuntime                string      `json:"chat_runtime"`
	ChatAcpAgentID             pgtype.Text `json:"chat_acp_agent_id"`
	ChatAcpProjectPath         string      `json:"chat_acp_project_path"`
	ChatAcpProjectMode         string      `json:"chat_acp_project_mode"`
	HeartbeatModelID           pgtype.UUID `json:"heartbeat_model_id"`
	CompactionModelIDSet       bool        `json:"compaction_model_id_set"`
	CompactionModelID          pgtype.UUID `json:"compaction_model_id"`
	SearchProviderID           pgtype.UUID `json:"search_provider_id"`
	FetchProviderIDSet         bool        `json:"fetch_provider_id_set"`
	FetchProviderID            pgtype.UUID `json:"fetch_provider_id"`
	MemoryProviderID           pgtype.UUID `json:"memory_provider_id"`
	ImageModelID               pgtype.UUID `json:"image_model_id"`
	TtsModelID                 pgtype.UUID `json:"tts_model_id"`
	TranscriptionModelID       pgtype.UUID `json:"transcription_model_id"`
	VideoModelID               pgtype.UUID `json:"video_model_id"`
	PersistFullToolResults     bool        `json:"persist_full_tool_results"`
	ShowToolCallsInIm          bool        `json:"show_tool_calls_in_im"`
	ToolApprovalConfig         []byte      `json:"tool_approval_config"`
	DisplayEnabled             bool        `json:"display_enabled"`
	OverlayProvider            string      `json:"overlay_provider"`
	OverlayEnabled             bool        `json:"overlay_enabled"`
	OverlayConfig              []byte      `json:"overlay_config"`
	CommandUiLanguage          string      `json:"command_ui_language"`
	ID                         pgtype.UUID `json:"id"`
}

type UpsertBotSettingsRow struct {
	BotID                   pgtype.UUID `json:"bot_id"`
	Language                string      `json:"language"`
	ReasoningEnabled        bool        `json:"reasoning_enabled"`
	ReasoningEffort         string      `json:"reasoning_effort"`
	HeartbeatEnabled        bool        `json:"heartbeat_enabled"`
	HeartbeatInterval       int32       `json:"heartbeat_interval"`
	HeartbeatPrompt         string      `json:"heartbeat_prompt"`
	CompactionEnabled       bool        `json:"compaction_enabled"`
	CompactionThreshold     int32       `json:"compaction_threshold"`
	CompactionTargetPercent pgtype.Int4 `json:"compaction_target_percent"`
	Timezone                pgtype.Text `json:"timezone"`
	ChatModelID             pgtype.UUID `json:"chat_model_id"`
	ChatRuntime             string      `json:"chat_runtime"`
	ChatAcpAgentID          pgtype.Text `json:"chat_acp_agent_id"`
	ChatAcpProjectPath      string      `json:"chat_acp_project_path"`
	ChatAcpProjectMode      string      `json:"chat_acp_project_mode"`
	HeartbeatModelID        pgtype.UUID `json:"heartbeat_model_id"`
	CompactionModelID       pgtype.UUID `json:"compaction_model_id"`
	SearchProviderID        pgtype.UUID `json:"search_provider_id"`
	FetchProviderID         pgtype.UUID `json:"fetch_provider_id"`
	MemoryProviderID        pgtype.UUID `json:"memory_provider_id"`
	ImageModelID            pgtype.UUID `json:"image_model_id"`
	TtsModelID              pgtype.UUID `json:"tts_model_id"`
	TranscriptionModelID    pgtype.UUID `json:"transcription_model_id"`
	VideoModelID            pgtype.UUID `json:"video_model_id"`
	PersistFullToolResults  bool        `json:"persist_full_tool_results"`
	ShowToolCallsInIm       bool        `json:"show_tool_calls_in_im"`
	ToolApprovalConfig      []byte      `json:"tool_approval_config"`
	DisplayEnabled          bool        `json:"display_enabled"`
	OverlayProvider         string      `json:"overlay_provider"`
	OverlayEnabled          bool        `json:"overlay_enabled"`
	OverlayConfig           []byte      `json:"overlay_config"`
	CommandUiLanguage       string      `json:"command_ui_language"`
}

func (q *Queries) UpsertBotSettings(ctx context.Context, arg UpsertBotSettingsParams) (UpsertBotSettingsRow, error) {
	row := q.db.QueryRow(ctx, upsertBotSettings,
		arg.Language,
		arg.ReasoningEnabled,
		arg.ReasoningEffort,
		arg.HeartbeatEnabled,
		arg.HeartbeatInterval,
		arg.HeartbeatPrompt,
		arg.CompactionEnabled,
		arg.CompactionThreshold,
		arg.CompactionTargetPercentSet,
		arg.CompactionTargetPercent,
		arg.Timezone,
		arg.ChatModelID,
		arg.ChatRuntime,
		arg.ChatAcpAgentID,
		arg.ChatAcpProjectPath,
		arg.ChatAcpProjectMode,
		arg.HeartbeatModelID,
		arg.CompactionModelIDSet,
		arg.CompactionModelID,
		arg.SearchProviderID,
		arg.FetchProviderIDSet,
		arg.FetchProviderID,
		arg.MemoryProviderID,
		arg.ImageModelID,
		arg.TtsModelID,
		arg.TranscriptionModelID,
		arg.VideoModelID,
		arg.PersistFullToolResults,
		arg.ShowToolCallsInIm,
		arg.ToolApprovalConfig,
		arg.DisplayEnabled,
		arg.OverlayProvider,
		arg.OverlayEnabled,
		arg.OverlayConfig,
		arg.CommandUiLanguage,
		arg.ID,
	)
	var i UpsertBotSettingsRow
	err := row.Scan(
		&i.BotID,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionTargetPercent,
		&i.Timezone,
		&i.ChatModelID,
		&i.ChatRuntime,
		&i.ChatAcpAgentID,
		&i.ChatAcpProjectPath,
		&i.ChatAcpProjectMode,
		&i.HeartbeatModelID,
		&i.CompactionModelID,
		&i.SearchProviderID,
		&i.FetchProviderID,
		&i.MemoryProviderID,
		&i.ImageModelID,
		&i.TtsModelID,
		&i.TranscriptionModelID,
		&i.VideoModelID,
		&i.PersistFullToolResults,
		&i.ShowToolCallsInIm,
		&i.ToolApprovalConfig,
		&i.DisplayEnabled,
		&i.OverlayProvider,
		&i.OverlayEnabled,
		&i.OverlayConfig,
		&i.CommandUiLanguage,
	)
	return i, err
}
