// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subagents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubagentConfig = `-- name: CreateSubagentConfig :one
INSERT INTO subagent_configs (
  session_id,
  model_uuid,
  model_id,
  provider_name,
  forked
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING team_id, session_id, model_uuid, model_id, provider_name, forked, created_at, updated_at
`

type CreateSubagentConfigParams struct {
	SessionID    pgtype.UUID `json:"session_id"`
	ModelUuid    pgtype.UUID `json:"model_uuid"`
	ModelID      string      `json:"model_id"`
	ProviderName string      `json:"provider_name"`
	Forked       bool        `json:"forked"`
}

func (q *Queries) CreateSubagentConfig(ctx context.Context, arg CreateSubagentConfigParams) (SubagentConfig, error) {
	row := q.db.QueryRow(ctx, createSubagentConfig,
		arg.SessionID,
		arg.ModelUuid,
		arg.ModelID,
		arg.ProviderName,
		arg.Forked,
	)
	var i SubagentConfig
	err := row.Scan(
		&i.TeamID,
		&i.SessionID,
		&i.ModelUuid,
		&i.ModelID,
		&i.ProviderName,
		&i.Forked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubagentForkContext = `-- name: CreateSubagentForkContext :one
WITH target_session AS MATERIALIZED (
  SELECT child.id, child.bot_id, child.team_id
  FROM bot_sessions child
  JOIN bot_sessions parent
    ON parent.team_id = public.sophia_current_team_id()
   AND parent.id = $1
   AND parent.id = child.parent_session_id
   AND parent.bot_id = child.bot_id
   AND parent.deleted_at IS NULL
  WHERE child.team_id = public.sophia_current_team_id()
    AND child.id = $2
    AND child.type = 'subagent'
    AND child.deleted_at IS NULL
),
context_entries AS MATERIALIZED (
  SELECT entry, ordinality::bigint AS position
  FROM jsonb_array_elements($3::jsonb)
       WITH ORDINALITY AS items(entry, ordinality)
),
prepared_messages AS MATERIALIZED (
  SELECT
    gen_random_uuid() AS id,
    gen_random_uuid() AS turn_id,
    entries.position,
    source.id AS source_id,
    target.id AS session_id,
    target.bot_id,
    source.sender_channel_identity_id,
    source.sender_account_user_id,
    source.source_message_id,
    source.source_reply_to_message_id,
    COALESCE(source.role, entries.entry->>'role') AS role,
    COALESCE(source.content, entries.entry->'message') AS content,
    COALESCE(source.metadata, '{}'::jsonb)
      || jsonb_build_object(
        'context_scope', 'subagent_fork',
        'context_version', 1,
        'source_session_id', $1::text
      )
      || CASE
        WHEN source.id IS NULL THEN '{}'::jsonb
        ELSE jsonb_build_object('source_message_id', source.id::text)
      END AS metadata,
    COALESCE(source.runtime_type, 'model') AS runtime_type,
    source.model_id,
    source.display_text,
    COALESCE(source.created_at, now()) AS created_at
  FROM context_entries entries
  CROSS JOIN target_session target
  LEFT JOIN bot_history_messages source
    ON source.team_id = public.sophia_current_team_id()
   AND source.id = NULLIF(entries.entry->>'source_message_id', '')::uuid
   AND source.session_id = $1
   AND source.bot_id = target.bot_id
),
updated_session AS (
  UPDATE bot_sessions session
  SET next_turn_position = (SELECT count(*)::bigint + 1 FROM context_entries)
  FROM target_session target
  WHERE session.team_id = public.sophia_current_team_id()
    AND session.id = target.id
  RETURNING session.id
),
inserted_messages AS (
  INSERT INTO bot_history_messages (
    id,
    bot_id,
    session_id,
    sender_channel_identity_id,
    sender_account_user_id,
    source_message_id,
    source_reply_to_message_id,
    role,
    content,
    metadata,
    usage,
    session_mode,
    runtime_type,
    model_id,
    display_text,
    turn_id,
    turn_position,
    turn_message_seq,
    turn_visible,
    created_at
  )
  SELECT
    prepared.id,
    prepared.bot_id,
    prepared.session_id,
    prepared.sender_channel_identity_id,
    prepared.sender_account_user_id,
    prepared.source_message_id,
    prepared.source_reply_to_message_id,
    prepared.role,
    prepared.content,
    prepared.metadata,
    NULL,
    'subagent',
    prepared.runtime_type,
    prepared.model_id,
    prepared.display_text,
    prepared.turn_id,
    prepared.position,
    1,
    false,
    prepared.created_at
  FROM prepared_messages prepared
  JOIN updated_session updated ON updated.id = prepared.session_id
  RETURNING id
),
copied_assets AS (
  INSERT INTO bot_history_message_assets (
    message_id,
    role,
    ordinal,
    content_hash,
    mime,
    size_bytes,
    storage_key,
    name,
    metadata
  )
  SELECT
    prepared.id,
    asset.role,
    asset.ordinal,
    asset.content_hash,
    asset.mime,
    asset.size_bytes,
    asset.storage_key,
    asset.name,
    asset.metadata
  FROM prepared_messages prepared
  JOIN inserted_messages inserted ON inserted.id = prepared.id
  JOIN bot_history_message_assets asset
    ON asset.team_id = public.sophia_current_team_id()
   AND asset.message_id = prepared.source_id
  RETURNING id
)
SELECT
  (SELECT count(*)::bigint FROM inserted_messages) AS inserted_count,
  (SELECT count(*)::bigint FROM copied_assets) AS copied_asset_count
`

type CreateSubagentForkContextParams struct {
	ParentSessionID pgtype.UUID `json:"parent_session_id"`
	SessionID       pgtype.UUID `json:"session_id"`
	ContextMessages []byte      `json:"context_messages"`
}

type CreateSubagentForkContextRow struct {
	InsertedCount    int64 `json:"inserted_count"`
	CopiedAssetCount int64 `json:"copied_asset_count"`
}

func (q *Queries) CreateSubagentForkContext(ctx context.Context, arg CreateSubagentForkContextParams) (CreateSubagentForkContextRow, error) {
	row := q.db.QueryRow(ctx, createSubagentForkContext, arg.ParentSessionID, arg.SessionID, arg.ContextMessages)
	var i CreateSubagentForkContextRow
	err := row.Scan(&i.InsertedCount, &i.CopiedAssetCount)
	return i, err
}

const getSubagentConfig = `-- name: GetSubagentConfig :one
SELECT team_id, session_id, model_uuid, model_id, provider_name, forked, created_at, updated_at
FROM subagent_configs
WHERE session_id = $1
`

func (q *Queries) GetSubagentConfig(ctx context.Context, sessionID pgtype.UUID) (SubagentConfig, error) {
	row := q.db.QueryRow(ctx, getSubagentConfig, sessionID)
	var i SubagentConfig
	err := row.Scan(
		&i.TeamID,
		&i.SessionID,
		&i.ModelUuid,
		&i.ModelID,
		&i.ProviderName,
		&i.Forked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubagentForkContext = `-- name: ListSubagentForkContext :many
SELECT role, content
FROM bot_history_messages
WHERE team_id = public.sophia_current_team_id()
  AND session_id = $1
  AND session_mode = 'subagent'
  AND turn_visible = false
  AND metadata->>'context_scope' = 'subagent_fork'
ORDER BY turn_position ASC, turn_message_seq ASC, created_at ASC, id ASC
`

type ListSubagentForkContextRow struct {
	Role    string `json:"role"`
	Content []byte `json:"content"`
}

func (q *Queries) ListSubagentForkContext(ctx context.Context, sessionID pgtype.UUID) ([]ListSubagentForkContextRow, error) {
	rows, err := q.db.Query(ctx, listSubagentForkContext, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubagentForkContextRow
	for rows.Next() {
		var i ListSubagentForkContextRow
		if err := rows.Scan(&i.Role, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
