// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_runtimes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearBotRemoteRuntimePrimary = `-- name: ClearBotRemoteRuntimePrimary :exec
UPDATE bot_remote_runtime_bindings
SET is_primary = FALSE,
    updated_at = CASE WHEN is_primary THEN now() ELSE updated_at END
WHERE team_id = public.sophia_current_team_id()
  AND bot_id = $1
`

func (q *Queries) ClearBotRemoteRuntimePrimary(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearBotRemoteRuntimePrimary, botID)
	return err
}

const createOrUpdateBotRemoteRuntimeMount = `-- name: CreateOrUpdateBotRemoteRuntimeMount :one
INSERT INTO bot_remote_runtime_bindings (bot_id, runtime_id)
SELECT b.id, r.id
FROM bots b
JOIN user_runtimes r
  ON r.id = $1
 AND r.team_id = public.sophia_current_team_id()
 AND r.user_id = b.owner_user_id
 AND r.revoked_at IS NULL
JOIN team_members owner_membership
  ON owner_membership.team_id = public.sophia_current_team_id()
 AND owner_membership.user_id = b.owner_user_id
 AND owner_membership.is_active = TRUE
JOIN users owner ON owner.id = owner_membership.user_id AND owner.is_active = TRUE
WHERE b.team_id = public.sophia_current_team_id()
  AND b.id = $2
ON CONFLICT (team_id, bot_id, runtime_id) DO UPDATE SET
  updated_at = now()
RETURNING id
`

type CreateOrUpdateBotRemoteRuntimeMountParams struct {
	RuntimeID pgtype.UUID `json:"runtime_id"`
	BotID     pgtype.UUID `json:"bot_id"`
}

func (q *Queries) CreateOrUpdateBotRemoteRuntimeMount(ctx context.Context, arg CreateOrUpdateBotRemoteRuntimeMountParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createOrUpdateBotRemoteRuntimeMount, arg.RuntimeID, arg.BotID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createUserRuntime = `-- name: CreateUserRuntime :one
INSERT INTO user_runtimes (user_id, name, api_token)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, api_token, revoked_at, created_at, updated_at, team_id
`

type CreateUserRuntimeParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Name     string      `json:"name"`
	ApiToken string      `json:"api_token"`
}

func (q *Queries) CreateUserRuntime(ctx context.Context, arg CreateUserRuntimeParams) (UserRuntime, error) {
	row := q.db.QueryRow(ctx, createUserRuntime, arg.UserID, arg.Name, arg.ApiToken)
	var i UserRuntime
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ApiToken,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const deleteBotRemoteRuntimeMount = `-- name: DeleteBotRemoteRuntimeMount :one
DELETE FROM bot_remote_runtime_bindings
WHERE team_id = public.sophia_current_team_id()
  AND bot_id = $1
  AND id = $2
RETURNING id
`

type DeleteBotRemoteRuntimeMountParams struct {
	BotID    pgtype.UUID `json:"bot_id"`
	TargetID pgtype.UUID `json:"target_id"`
}

func (q *Queries) DeleteBotRemoteRuntimeMount(ctx context.Context, arg DeleteBotRemoteRuntimeMountParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteBotRemoteRuntimeMount, arg.BotID, arg.TargetID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getBotRemoteRuntimeMount = `-- name: GetBotRemoteRuntimeMount :one
SELECT
  binding.id,
  binding.bot_id,
  binding.runtime_id,
  binding.is_primary,
  binding.tool_approval_config,
  binding.created_at,
  binding.updated_at,
  runtime.name AS runtime_name,
  runtime.user_id AS runtime_user_id,
  (runtime.revoked_at IS NOT NULL OR NOT owner.is_active OR NOT owner_membership.is_active) AS runtime_unavailable,
  bot.owner_user_id AS bot_owner_user_id
FROM bot_remote_runtime_bindings binding
JOIN user_runtimes runtime ON runtime.id = binding.runtime_id AND runtime.team_id = public.sophia_current_team_id()
JOIN bots bot ON bot.id = binding.bot_id AND bot.team_id = public.sophia_current_team_id()
JOIN team_members owner_membership
  ON owner_membership.team_id = public.sophia_current_team_id()
 AND owner_membership.user_id = bot.owner_user_id
JOIN users owner ON owner.id = owner_membership.user_id
WHERE binding.team_id = public.sophia_current_team_id()
  AND binding.bot_id = $1
  AND binding.id = $2
`

type GetBotRemoteRuntimeMountParams struct {
	BotID    pgtype.UUID `json:"bot_id"`
	TargetID pgtype.UUID `json:"target_id"`
}

type GetBotRemoteRuntimeMountRow struct {
	ID                 pgtype.UUID        `json:"id"`
	BotID              pgtype.UUID        `json:"bot_id"`
	RuntimeID          pgtype.UUID        `json:"runtime_id"`
	IsPrimary          bool               `json:"is_primary"`
	ToolApprovalConfig []byte             `json:"tool_approval_config"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	RuntimeName        string             `json:"runtime_name"`
	RuntimeUserID      pgtype.UUID        `json:"runtime_user_id"`
	RuntimeUnavailable pgtype.Bool        `json:"runtime_unavailable"`
	BotOwnerUserID     pgtype.UUID        `json:"bot_owner_user_id"`
}

func (q *Queries) GetBotRemoteRuntimeMount(ctx context.Context, arg GetBotRemoteRuntimeMountParams) (GetBotRemoteRuntimeMountRow, error) {
	row := q.db.QueryRow(ctx, getBotRemoteRuntimeMount, arg.BotID, arg.TargetID)
	var i GetBotRemoteRuntimeMountRow
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RuntimeID,
		&i.IsPrimary,
		&i.ToolApprovalConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RuntimeName,
		&i.RuntimeUserID,
		&i.RuntimeUnavailable,
		&i.BotOwnerUserID,
	)
	return i, err
}

const getPrimaryBotRemoteRuntimeMount = `-- name: GetPrimaryBotRemoteRuntimeMount :one
SELECT
  binding.id,
  binding.bot_id,
  binding.runtime_id,
  binding.is_primary,
  binding.tool_approval_config,
  binding.created_at,
  binding.updated_at,
  runtime.name AS runtime_name,
  runtime.user_id AS runtime_user_id,
  (runtime.revoked_at IS NOT NULL OR NOT owner.is_active OR NOT owner_membership.is_active) AS runtime_unavailable,
  bot.owner_user_id AS bot_owner_user_id
FROM bot_remote_runtime_bindings binding
JOIN user_runtimes runtime ON runtime.id = binding.runtime_id AND runtime.team_id = public.sophia_current_team_id()
JOIN bots bot ON bot.id = binding.bot_id AND bot.team_id = public.sophia_current_team_id()
JOIN team_members owner_membership
  ON owner_membership.team_id = public.sophia_current_team_id()
 AND owner_membership.user_id = bot.owner_user_id
JOIN users owner ON owner.id = owner_membership.user_id
WHERE binding.team_id = public.sophia_current_team_id()
  AND binding.bot_id = $1
  AND binding.is_primary = TRUE
`

type GetPrimaryBotRemoteRuntimeMountRow struct {
	ID                 pgtype.UUID        `json:"id"`
	BotID              pgtype.UUID        `json:"bot_id"`
	RuntimeID          pgtype.UUID        `json:"runtime_id"`
	IsPrimary          bool               `json:"is_primary"`
	ToolApprovalConfig []byte             `json:"tool_approval_config"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	RuntimeName        string             `json:"runtime_name"`
	RuntimeUserID      pgtype.UUID        `json:"runtime_user_id"`
	RuntimeUnavailable pgtype.Bool        `json:"runtime_unavailable"`
	BotOwnerUserID     pgtype.UUID        `json:"bot_owner_user_id"`
}

func (q *Queries) GetPrimaryBotRemoteRuntimeMount(ctx context.Context, botID pgtype.UUID) (GetPrimaryBotRemoteRuntimeMountRow, error) {
	row := q.db.QueryRow(ctx, getPrimaryBotRemoteRuntimeMount, botID)
	var i GetPrimaryBotRemoteRuntimeMountRow
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RuntimeID,
		&i.IsPrimary,
		&i.ToolApprovalConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RuntimeName,
		&i.RuntimeUserID,
		&i.RuntimeUnavailable,
		&i.BotOwnerUserID,
	)
	return i, err
}

const getUserRuntimeByAPIToken = `-- name: GetUserRuntimeByAPIToken :one
SELECT runtime.id, runtime.user_id, runtime.name, runtime.api_token, runtime.revoked_at, runtime.created_at, runtime.updated_at, runtime.team_id
FROM user_runtimes runtime
JOIN team_members owner_membership
  ON owner_membership.team_id = public.sophia_current_team_id()
 AND owner_membership.user_id = runtime.user_id
 AND owner_membership.is_active = TRUE
JOIN users owner ON owner.id = owner_membership.user_id AND owner.is_active = TRUE
WHERE runtime.team_id = public.sophia_current_team_id()
  AND runtime.api_token = $1
  AND runtime.revoked_at IS NULL
`

func (q *Queries) GetUserRuntimeByAPIToken(ctx context.Context, apiToken string) (UserRuntime, error) {
	row := q.db.QueryRow(ctx, getUserRuntimeByAPIToken, apiToken)
	var i UserRuntime
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ApiToken,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const listBotRemoteRuntimeMounts = `-- name: ListBotRemoteRuntimeMounts :many
SELECT
  binding.id,
  binding.bot_id,
  binding.runtime_id,
  binding.is_primary,
  binding.tool_approval_config,
  binding.created_at,
  binding.updated_at,
  runtime.name AS runtime_name,
  runtime.user_id AS runtime_user_id,
  (runtime.revoked_at IS NOT NULL OR NOT owner.is_active OR NOT owner_membership.is_active) AS runtime_unavailable,
  bot.owner_user_id AS bot_owner_user_id
FROM bot_remote_runtime_bindings binding
JOIN user_runtimes runtime ON runtime.id = binding.runtime_id AND runtime.team_id = public.sophia_current_team_id()
JOIN bots bot ON bot.id = binding.bot_id AND bot.team_id = public.sophia_current_team_id()
JOIN team_members owner_membership
  ON owner_membership.team_id = public.sophia_current_team_id()
 AND owner_membership.user_id = bot.owner_user_id
JOIN users owner ON owner.id = owner_membership.user_id
WHERE binding.team_id = public.sophia_current_team_id()
  AND binding.bot_id = $1
ORDER BY binding.created_at ASC, binding.id ASC
`

type ListBotRemoteRuntimeMountsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	BotID              pgtype.UUID        `json:"bot_id"`
	RuntimeID          pgtype.UUID        `json:"runtime_id"`
	IsPrimary          bool               `json:"is_primary"`
	ToolApprovalConfig []byte             `json:"tool_approval_config"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	RuntimeName        string             `json:"runtime_name"`
	RuntimeUserID      pgtype.UUID        `json:"runtime_user_id"`
	RuntimeUnavailable pgtype.Bool        `json:"runtime_unavailable"`
	BotOwnerUserID     pgtype.UUID        `json:"bot_owner_user_id"`
}

func (q *Queries) ListBotRemoteRuntimeMounts(ctx context.Context, botID pgtype.UUID) ([]ListBotRemoteRuntimeMountsRow, error) {
	rows, err := q.db.Query(ctx, listBotRemoteRuntimeMounts, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBotRemoteRuntimeMountsRow
	for rows.Next() {
		var i ListBotRemoteRuntimeMountsRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.RuntimeID,
			&i.IsPrimary,
			&i.ToolApprovalConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RuntimeName,
			&i.RuntimeUserID,
			&i.RuntimeUnavailable,
			&i.BotOwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRuntimes = `-- name: ListUserRuntimes :many
SELECT id, user_id, name, api_token, revoked_at, created_at, updated_at, team_id FROM user_runtimes
WHERE team_id = public.sophia_current_team_id()
  AND user_id = $1 AND revoked_at IS NULL
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListUserRuntimes(ctx context.Context, userID pgtype.UUID) ([]UserRuntime, error) {
	rows, err := q.db.Query(ctx, listUserRuntimes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRuntime
	for rows.Next() {
		var i UserRuntime
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ApiToken,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserRuntime = `-- name: RevokeUserRuntime :one
UPDATE user_runtimes
SET revoked_at = now(), updated_at = now()
WHERE team_id = public.sophia_current_team_id()
  AND id = $1 AND user_id = $2 AND revoked_at IS NULL
RETURNING id, user_id, name, api_token, revoked_at, created_at, updated_at, team_id
`

type RevokeUserRuntimeParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeUserRuntime(ctx context.Context, arg RevokeUserRuntimeParams) (UserRuntime, error) {
	row := q.db.QueryRow(ctx, revokeUserRuntime, arg.ID, arg.UserID)
	var i UserRuntime
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ApiToken,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const setBotRemoteRuntimePrimary = `-- name: SetBotRemoteRuntimePrimary :execrows
UPDATE bot_remote_runtime_bindings
SET is_primary = TRUE,
    updated_at = CASE WHEN is_primary THEN updated_at ELSE now() END
WHERE team_id = public.sophia_current_team_id()
  AND bot_id = $1
  AND id = $2
`

type SetBotRemoteRuntimePrimaryParams struct {
	BotID    pgtype.UUID `json:"bot_id"`
	TargetID pgtype.UUID `json:"target_id"`
}

func (q *Queries) SetBotRemoteRuntimePrimary(ctx context.Context, arg SetBotRemoteRuntimePrimaryParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBotRemoteRuntimePrimary, arg.BotID, arg.TargetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBotRemoteRuntimeMountToolApproval = `-- name: UpdateBotRemoteRuntimeMountToolApproval :one
UPDATE bot_remote_runtime_bindings
SET tool_approval_config = $1,
    updated_at = now()
WHERE team_id = public.sophia_current_team_id()
  AND bot_id = $2
  AND id = $3
RETURNING id
`

type UpdateBotRemoteRuntimeMountToolApprovalParams struct {
	ToolApprovalConfig []byte      `json:"tool_approval_config"`
	BotID              pgtype.UUID `json:"bot_id"`
	TargetID           pgtype.UUID `json:"target_id"`
}

func (q *Queries) UpdateBotRemoteRuntimeMountToolApproval(ctx context.Context, arg UpdateBotRemoteRuntimeMountToolApprovalParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateBotRemoteRuntimeMountToolApproval, arg.ToolApprovalConfig, arg.BotID, arg.TargetID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
