// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/rpc/runtimepb/runtime.proto

package runtimepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_internal_rpc_runtimepb_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_runtimepb_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_runtimepb_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_internal_rpc_runtimepb_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_runtimepb_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_runtimepb_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *CallResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_internal_rpc_runtimepb_runtime_proto protoreflect.FileDescriptor

const file_internal_rpc_runtimepb_runtime_proto_rawDesc = "" +
	"\n" +
	"$internal/rpc/runtimepb/runtime.proto\x12\x10memoh.runtime.v1\"?\n" +
	"\vCallRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"(\n" +
	"\fCallResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload2W\n" +
	"\x0eRuntimeService\x12E\n" +
	"\x04Call\x12\x1d.memoh.runtime.v1.CallRequest\x1a\x1e.memoh.runtime.v1.CallResponseB1Z/github.com/memohai/memoh/internal/rpc/runtimepbb\x06proto3"

var (
	file_internal_rpc_runtimepb_runtime_proto_rawDescOnce sync.Once
	file_internal_rpc_runtimepb_runtime_proto_rawDescData []byte
)

func file_internal_rpc_runtimepb_runtime_proto_rawDescGZIP() []byte {
	file_internal_rpc_runtimepb_runtime_proto_rawDescOnce.Do(func() {
		file_internal_rpc_runtimepb_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_runtimepb_runtime_proto_rawDesc), len(file_internal_rpc_runtimepb_runtime_proto_rawDesc)))
	})
	return file_internal_rpc_runtimepb_runtime_proto_rawDescData
}

var file_internal_rpc_runtimepb_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_rpc_runtimepb_runtime_proto_goTypes = []any{
	(*CallRequest)(nil),  // 0: memoh.runtime.v1.CallRequest
	(*CallResponse)(nil), // 1: memoh.runtime.v1.CallResponse
}
var file_internal_rpc_runtimepb_runtime_proto_depIdxs = []int32{
	0, // 0: memoh.runtime.v1.RuntimeService.Call:input_type -> memoh.runtime.v1.CallRequest
	1, // 1: memoh.runtime.v1.RuntimeService.Call:output_type -> memoh.runtime.v1.CallResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_rpc_runtimepb_runtime_proto_init() }
func file_internal_rpc_runtimepb_runtime_proto_init() {
	if File_internal_rpc_runtimepb_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_runtimepb_runtime_proto_rawDesc), len(file_internal_rpc_runtimepb_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_rpc_runtimepb_runtime_proto_goTypes,
		DependencyIndexes: file_internal_rpc_runtimepb_runtime_proto_depIdxs,
		MessageInfos:      file_internal_rpc_runtimepb_runtime_proto_msgTypes,
	}.Build()
	File_internal_rpc_runtimepb_runtime_proto = out.File
	file_internal_rpc_runtimepb_runtime_proto_goTypes = nil
	file_internal_rpc_runtimepb_runtime_proto_depIdxs = nil
}
