// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type MemoryNodeEmbedding struct {
	BotID      pgtype.UUID        `json:"bot_id"`
	NodeID     string             `json:"node_id"`
	ModelID    pgtype.UUID        `json:"model_id"`
	Dimensions int32              `json:"dimensions"`
	BodyHash   string             `json:"body_hash"`
	Embedding  pgvector_go.Vector `json:"embedding"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TeamID     pgtype.UUID        `json:"team_id"`
}
