export interface ProviderPreset {
  id: string
  name: string
  registryName?: string
  clientType: string
  baseUrl: string
  icon?: string
  source: string
  requiresApiKey?: boolean
  requiresBaseUrl?: boolean
  domain?: 'llm' | 'video' | 'speech' | 'transcription'
}

export const providerPresets: ProviderPreset[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    clientType: 'openai-responses',
    baseUrl: 'https://api.openai.com/v1',
    icon: 'openai',
    source: 'openai.yaml',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    clientType: 'anthropic-messages',
    baseUrl: 'https://api.anthropic.com',
    icon: 'anthropic',
    source: 'anthropic.yaml',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    clientType: 'openai-completions',
    baseUrl: 'https://openrouter.ai/api/v1',
    icon: 'openrouter',
    source: 'openrouter.yaml',
  },
  {
    id: 'zai',
    name: 'Z.AI GLM',
    registryName: '智谱AI / Z.AI / GLM',
    clientType: 'openai-completions',
    baseUrl: 'https://api.z.ai/api/paas/v4',
    icon: 'zhipu-color',
    source: 'zai.yaml',
  },
  {
    id: 'zhipu',
    name: 'Zhipu AI',
    registryName: '智谱AI / BigModel / GLM',
    clientType: 'openai-completions',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    icon: 'zhipu-color',
    source: 'zhipu.yaml',
  },
  {
    id: 'together',
    name: 'Together AI',
    clientType: 'openai-completions',
    baseUrl: 'https://api.together.xyz/v1',
    icon: 'together-color',
    source: 'together.yaml',
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    clientType: 'openai-completions',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    icon: 'fireworks-color',
    source: 'fireworks.yaml',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    clientType: 'openai-completions',
    baseUrl: 'https://api.perplexity.ai',
    icon: 'perplexity-color',
    source: 'perplexity.yaml',
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    clientType: 'openai-completions',
    baseUrl: 'https://api.cerebras.ai/v1',
    icon: 'cerebras-color',
    source: 'cerebras.yaml',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare Workers AI',
    clientType: 'openai-completions',
    baseUrl: 'https://api.cloudflare.com/client/v4/accounts/<account_id>/ai/v1',
    icon: 'cloudflare',
    source: 'cloudflare.yaml',
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI',
    clientType: 'openai-completions',
    baseUrl: 'https://<resource>.openai.azure.com/openai/v1',
    icon: 'azure-color',
    source: 'azure-openai.yaml',
  },
  {
    id: 'google',
    name: 'Google Gemini',
    registryName: 'Google',
    clientType: 'google-generative-ai',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    icon: 'gemini-color',
    source: 'google.yaml',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    clientType: 'openai-completions',
    baseUrl: 'https://api.deepseek.com/v1',
    icon: 'deepseek-color',
    source: 'deepseek.yaml',
  },
  {
    id: 'moonshot',
    name: 'Moonshot',
    clientType: 'openai-completions',
    baseUrl: 'https://api.moonshot.cn/v1',
    icon: 'moonshot',
    source: 'moonshot.yaml',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    registryName: 'Minimax',
    clientType: 'openai-completions',
    baseUrl: 'https://api.minimaxi.com/v1',
    icon: 'minimax-color',
    source: 'minimax.yaml',
  },
  {
    id: 'xai',
    name: 'xAI Grok',
    registryName: 'xAI (Grok)',
    clientType: 'openai-responses',
    baseUrl: 'https://api.x.ai/v1',
    icon: 'xai',
    source: 'xai.yaml',
  },
  {
    id: 'groq',
    name: 'Groq',
    clientType: 'openai-completions',
    baseUrl: 'https://api.groq.com/openai/v1',
    icon: 'groq',
    source: 'groq.yaml',
  },
  {
    id: 'mistral',
    name: 'Mistral',
    clientType: 'openai-completions',
    baseUrl: 'https://api.mistral.ai/v1',
    icon: 'mistral-color',
    source: 'mistral.yaml',
  },
  {
    id: 'qwen',
    name: 'Aliyun Bailian',
    clientType: 'openai-completions',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    icon: 'qwen-color',
    source: 'qwen.yaml',
  },
  {
    id: 'huggingface',
    name: 'HuggingFace',
    clientType: 'openai-completions',
    baseUrl: 'https://router.huggingface.co/hf-inference/v1',
    icon: 'huggingface-color',
    source: 'huggingface.yaml',
  },
  {
    id: 'ollama',
    name: 'Ollama',
    clientType: 'openai-completions',
    baseUrl: 'http://127.0.0.1:11434/v1',
    icon: 'ollama',
    source: 'ollama.yaml',
    requiresApiKey: false,
  },
  {
    id: 'lmstudio',
    name: 'LM Studio',
    clientType: 'openai-completions',
    baseUrl: 'http://127.0.0.1:1234/v1',
    icon: 'lmstudio',
    source: 'lmstudio.yaml',
    requiresApiKey: false,
  },
  {
    id: 'newapi',
    name: 'New API',
    clientType: 'openai-completions',
    baseUrl: 'https://your.new-api-provider.com',
    icon: 'newapi-color',
    source: 'newapi.yaml',
  },
  {
    id: 'openai-codex',
    name: 'OpenAI Codex',
    clientType: 'openai-codex',
    baseUrl: 'https://chatgpt.com/backend-api',
    icon: 'openai',
    source: 'codex.yaml',
    requiresApiKey: false,
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    clientType: 'github-copilot',
    baseUrl: '',
    icon: 'github-copilot',
    source: 'github-copilot.yaml',
    requiresApiKey: false,
  },
  {
    id: 'openrouter-video',
    name: 'OpenRouter',
    clientType: 'openrouter-video',
    baseUrl: 'https://openrouter.ai/api',
    icon: 'openrouter',
    source: 'openrouter-video.yaml',
    domain: 'video',
  },
  {
    id: 'modelark-video',
    name: 'ModelArk',
    clientType: 'modelark-video',
    baseUrl: 'https://ark.ap-southeast.bytepluses.com/api/v3',
    icon: 'modelark-color',
    source: 'modelark-video.yaml',
    domain: 'video',
  },
  {
    id: 'volcengine-video',
    name: 'Volcengine',
    clientType: 'volcengine-video',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    icon: 'volcengine-color',
    source: 'volcengine-video.yaml',
    domain: 'video',
  },
  // Speech (TTS) — created via the generic provider API, filtered by client_type.
  {
    id: 'edge-speech',
    name: 'Microsoft Edge',
    registryName: 'Edge',
    clientType: 'edge-speech',
    baseUrl: '',
    icon: 'microsoft',
    source: 'edge.yaml',
    requiresApiKey: false,
    requiresBaseUrl: false,
    domain: 'speech',
  },
  {
    id: 'openai-speech',
    name: 'OpenAI Speech',
    clientType: 'openai-speech',
    baseUrl: 'https://api.openai.com/v1',
    icon: 'openai',
    source: 'openai-speech.yaml',
    domain: 'speech',
  },
  {
    id: 'openrouter-speech',
    name: 'OpenRouter Speech',
    clientType: 'openrouter-speech',
    baseUrl: 'https://openrouter.ai/api/v1',
    icon: 'openrouter',
    source: 'openrouter-speech.yaml',
    domain: 'speech',
  },
  {
    id: 'elevenlabs-speech',
    name: 'ElevenLabs Speech',
    clientType: 'elevenlabs-speech',
    baseUrl: 'https://api.elevenlabs.io',
    icon: 'elevenlabs',
    source: 'elevenlabs-speech.yaml',
    domain: 'speech',
  },
  {
    id: 'deepgram-speech',
    name: 'Deepgram Speech',
    clientType: 'deepgram-speech',
    baseUrl: 'https://api.deepgram.com',
    icon: 'deepgram',
    source: 'deepgram-speech.yaml',
    domain: 'speech',
  },
  {
    id: 'minimax-speech',
    name: 'MiniMax Speech',
    clientType: 'minimax-speech',
    baseUrl: 'https://api.minimax.io',
    icon: 'minimax-color',
    source: 'minimax-speech.yaml',
    domain: 'speech',
  },
  {
    id: 'volcengine-speech',
    name: 'Volcengine Speech',
    clientType: 'volcengine-speech',
    baseUrl: 'https://sami.bytedance.com',
    icon: 'volcengine-color',
    source: 'volcengine-speech.yaml',
    domain: 'speech',
  },
  {
    id: 'alibabacloud-speech',
    name: 'Alibaba Cloud Speech',
    clientType: 'alibabacloud-speech',
    baseUrl: 'wss://dashscope.aliyuncs.com/api-ws/v1/inference/',
    icon: 'bailian-color',
    source: 'alibabacloud-speech.yaml',
    domain: 'speech',
  },
  {
    id: 'microsoft-speech',
    name: 'Microsoft Speech',
    registryName: 'Azure',
    clientType: 'microsoft-speech',
    baseUrl: '',
    icon: 'azure-color',
    source: 'microsoft-speech.yaml',
    requiresBaseUrl: false,
    domain: 'speech',
  },
  // Transcription (STT) — created via the generic provider API, filtered by client_type.
  {
    id: 'openai-transcription',
    name: 'OpenAI Transcription',
    clientType: 'openai-transcription',
    baseUrl: 'https://api.openai.com/v1',
    icon: 'openai',
    source: 'openai-transcription.yaml',
    domain: 'transcription',
  },
  {
    id: 'openrouter-transcription',
    name: 'OpenRouter Transcription',
    clientType: 'openrouter-transcription',
    baseUrl: 'https://openrouter.ai/api/v1',
    icon: 'openrouter',
    source: 'openrouter-transcription.yaml',
    domain: 'transcription',
  },
  {
    id: 'elevenlabs-transcription',
    name: 'ElevenLabs Transcription',
    clientType: 'elevenlabs-transcription',
    baseUrl: 'https://api.elevenlabs.io',
    icon: 'elevenlabs',
    source: 'elevenlabs-transcription.yaml',
    domain: 'transcription',
  },
  {
    id: 'deepgram-transcription',
    name: 'Deepgram Transcription',
    clientType: 'deepgram-transcription',
    baseUrl: 'https://api.deepgram.com',
    icon: 'deepgram',
    source: 'deepgram-transcription.yaml',
    domain: 'transcription',
  },
  {
    id: 'google-transcription',
    name: 'Google Transcription',
    clientType: 'google-transcription',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    icon: 'google-color',
    source: 'google-transcription.yaml',
    domain: 'transcription',
  },
]

const onboardingPresetIds = new Set([
  'openai',
  'anthropic',
  'openrouter',
  'google',
  'deepseek',
  'moonshot',
  'minimax',
  'xai',
])

export const onboardingProviderPresets = providerPresets.filter(preset =>
  onboardingPresetIds.has(preset.id),
)
